### ISSUE TITLE
Show progress/loader with information about the process when activating a configuration profile

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#108]
# Description
When a configuration profile (CP) is created, its state is `Incomplete`. When it's structure (stored as a JSON attribute in the same CP instance) is complete, validate against a JSON schema, its state changes automatically to `complete`.
At this point is the user who decides when to activate the CP to begin using it and permit its agents to use it. This process of "activating" the CP takes a few seconds or minutes, depending on the amount of data declared).
With this in mind, we need to show the user information about what's happening in the background and let him/her know it could take time to complete.

# Mockup
![Screenshot from 2021-09-10 12-49-16](https://user-images.githubusercontent.com/6996951/132881575-9e8581ee-dcd0-4ad1-a2d7-6d56c1dfb386.png)

**Comment by stuartasutton** [comment]
Very nice.
