### ISSUE TITLE
Mockup a new "Main Dashboard" page

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#112]
# Why
As continuation of #111, build a design a new Main Dashboard page with pertinent information about the status of the tool in real time.
As an important note, this will be a place to discuss whether to reflect the information from only active configuration profiles, or all of it, and other possible variants.

# Ideas
![Screenshot from 2021-09-14 15-23-17](https://user-images.githubusercontent.com/6996951/133312824-c702178f-fb20-4f0b-8f00-24152bba2e5d.png)

# Has to be done after #111

**Comment by richard0000** [comment]
# Mockup
![home-dashboard](https://user-images.githubusercontent.com/6996951/134081429-b82fe135-e14e-4362-bee4-12809b0c744f.png)

@stuartasutton What do you think of showing this information in the main dashboard view of an administrator?

**Comment by stuartasutton** [comment]
You mention "Incomplete" for a CP that lacks some component necessary to function. Is "Incomplete" the "Inactive" in the diagrams?  Obviously, I am still a little confused with the labels.

**Comment by stuartasutton** [comment]
Thanks!

**Comment by richard0000** [comment]
> > Looks very good! The only questions I might have align with your comment here regarding whether it should only be "active" configurations profiles. Somewhat depends on the exact definition of "active".
> 
> @stuartasutton "Active" configuration profiles are those that have completed all the necessary information to begin using it. E.g. a configuration profile that has declared DSO's information, Mapping Predicates, Abstract Classes, but doesn't have any agents declared yet, will be "Incomplete".
> 
> When that same Configuration Profile completes all the necessary information, it will automatically be transitioned to "Complete". Is the Configuration Profile administrator who decides when to "Activate" it, process in which all the information will be transformed into entities in the tool to begin using it.
> 
> As an alternative, we can also add here a counter for all the Configuration Profile states, having a filter by state, like this:
> 
> ### V2
> ![dashboard-main-v2](https://user-images.githubusercontent.com/6996951/134217644-fd7833b2-6653-401a-bdd8-e08c84a71a89.png)
> 
> ### V3
> ![main-dashboard-v3](https://user-images.githubusercontent.com/6996951/134222702-f09da600-62fb-4075-8936-89ed9fd17044.png)
> 
> Please, let me know your thoughts.

@stuartasutton please don't forget to give your vote on the mockups.

**Comment by stuartasutton** [comment]
I like version 3
