### ISSUE TITLE
Use the format converter in the Configuration Profile "Activate" action

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#114]
# Description
When a Configuration Profile is activated, and its state is "Complete", the tool parses the JSON structure and creates the described DSO's, agents, abstract classes, mapping predicates and more importantly for this issue, the schemes and concept schemes (Specifications and Vocabularies in the tool's logic).
These last steps works well with JSON-LD specifications, but not with the rest of the formats.

# Options
1. So one of the options is use the already working format converter to convert into JSON-LD any of the specified formats (RDF, XML, CSV, etc) in the activation process itself.

2. The other option is to use the format converter but in CP's creation/edition time, it is, when the user is loading the information.

# Preferred option and why
I recommend option 1., because we have a hard processing in the activation already, so it will not make a real difference to add this step in there, while we maintain clean of processing the creatino/edition of the CP in the view (while the CP is `incomplete`).

**Comment by stuartasutton** [comment]
@richard0000 , use your discretion here.
