### ISSUE TITLE
Add option to import a configuration profile by uploading a JSON structure

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#123]
# Description
Since a Configuration Profile's structure contains everything needed to build one, add an option on the create view, to create it by uploading a JSON structure.

# Steps
- [x] Add option in the "Create CP Box" at the Configuration Profile's index view.
- [x] Add a new view or popup to let the user upload the JSON file.
- [x] Validate and fail if it's not valid, allowing the user to correct and upload again. Note: validate against the "valid" JSON Schema, not the "complete" JSON schema, since we allow the creation of incomplete but valid Configuration Profiles.
- [x] Show a correct validation when it's valid, with a button to let the user confirm before begin the creation process.
- [x] Create the Configuration Profile in an "Incomplete" status, since it will be validated against the "complete" JSON schema automatically and change to complete if applies.

# Mockups
### From the Configuration Profiles List
![1](https://user-images.githubusercontent.com/6996951/140088596-3e4b892d-e4e6-4688-9179-fd555e4dd617.png)

### How to import
![2](https://user-images.githubusercontent.com/6996951/140088717-7437ba78-511a-4119-ac8e-934fb0705ff9.png)

### Validation and confirmation
![3](https://user-images.githubusercontent.com/6996951/140088793-bcd0b1db-7c7d-4a52-b88b-24c4aa493302.png)

**Comment by stuartasutton** [comment]
Yes! This is a very important function.
