### ISSUE TITLE
Adapt the abstract classes and predicate sets to be listed according to the configuration profile in the session

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#141]
# Description
The previous implementation (Phase 1) of the DESM, handled the automatic load of a set of abstract classes from a skos file in the directory of the application. Same for predicates.

Now with Configuration Profiles in place, we should change this to let the abstract classes be only those in the configuration profile corresponding to the session of the current user,

# Items to be covered
1- When the user is a mapper, it belongs to an organization (Data Standards Organization, DSO). This DSO will be part of a Configuration Profile (CP) and this last has Abstract Classes declared, only these should be listed. We assume if the user can login, the CP is in "active" state, so it should have abstract classes.
2- Same for mapping predicates.
3- When the user is an administrator (super admin or profile admin), we have two options:
  3.a- Deactivate the "begin mapping" option, because we don't know which CP to work with.
  3.b- Show a popup with the available Configuration Profiles and let the user select and use it while mapping. This option implies changes in the data model, since we don't have it defined for this use case at the moment.
4- When there's no session at all, we can always see the `Synthetic Spine Property Mapping By Category` list. In this section we have to define which abstract classes to display in the list. Again, we have two options:
  4.a- List all the abstract classes across all the active configuration profiles.
  4.b- Add a main filter to select the configuration profile first.
  
  @stuartasutton thoughts?

**Comment by stuartasutton** [comment]
Ricardo, I think I understand until I get down to 3. I can't contextualize either 3 or 4. When in the process do these happen?
