### ISSUE TITLE
Define and implement architectural changes to properly model the "spine" for each abstract class

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#152]
# Description
In order to allow users to map more than 1 specification to a single specification we need to separate (in the acse of the base, "add") the concepts of "base" and "spine".

When a user uploads a specification and links it to an abstract class that doesn't have any specification associated, it should immediately become the "base" specification for that abstract class. In addition we should create a "spine" to begin mapping to. This spine, in this initial instance would be just a copy of the "base" specification.

Once a user from a separate organization comes in to map a second specification by selecting the same abstract class, every term mapping should be performed between the "spine" and the uploaded/selected specification.

In this approach, when a third user (from a third DSO) comes in with a different specification, selecting the same abstract class, the mapping operation will be perform indeed between the "spine", which now contains additional terms from the previous mapping.

# Notes
- Add the design of a "base" as the spine is right now implemented.
- Add a new "spine" representation as a copy of the base, with possibility of growth with synthetic terms.
- Currently the synthetic terms are added to an alignment on a mapping entity, not to a specification (which could be the spine). We will need to consider the desired result when coming up with a solution to properly model the synthetic terms. We need the mapping model to track all the operations on an ongoing mapping. Maybe we can map the result of the mapping to the spine when the mapping finishes. In this case questions arises around the handling of many mappings at the same time, what would happen to the spine in this case? This issue is expanded in #153 .

**Comment by philbarker** [comment]
> In order to allow users to map more than 1 specification to a single specification we need to separate (in the acse of the base, "add") the concepts of "base" and "spine". 
...
> When a user uploads a specification and links it to an abstract class that doesn't have any specification associated, it should immediately become the "base" specification for that abstract class. 

I am not sure how useful or how good an idea it is to mark one of the specifications out as a special "base" class. I do not  think that we should hard-wire the first specification as the the base (if we have one).

For me this would work better as a workflow for creating the synthetic spine:
1. on configuration create an empty spine & upload details of the specifications to be mapped.
2. the first step of mapping (maybe done part of the configuration stage -- that'll keep it part of this project) would be to create a first cut spine. Two ways of doing this would be:
2.1 pick a specification and add all of it; or,
2.2 pick terms from several specs (e.g some that work well from spec A, others that work well from spec B)
3. (definitely now in the mapping, not config phase) add new terms to the spine where there is none to map to.

By not choosing not to label any spec as being the special "base" of the synthetic spine we would avoid confusion and unneccesary politicking about which spec gets special treatment. It would encourage a discussion from the beginning about which terms from which specs do a better job (whatever that means in the context of the mapping) of representing some aspect of the data.

**Comment by richard0000** [comment]
@philbarker I appreciate your comment and strategy details. From a technical standpoint I see 2 options:

## Option 1
- Create an empty spine at the time of creation of every abstract class.
- Then adding all the terms of the specification that gets linked when picking from the list in the configuration phase (this would add terms from only one spec but we can avoid calling it "the base").

## Option 2
- Also create an empty spine at the creation time of every abstract class.
- Then pick terms from several specs in configuration phase.

# Preferred option
Option 1 -> because it needs less work to be implemented. Option 2 needs mockups, discussion and it's compatible with Option 1 if we decide to implement it in the future.

@stuartasutton thoughts?

**Comment by philbarker** [comment]
Thanks @richard0000 I don't want to create more work than necessary! I'm happy to defer to @stuartasutton on this.
I think Option 1 would be fine, especially if there is the option of not doing the second point, that is leave the spine empty during configuration and only populating it when the mapping starts. Functionally I think that would give me everything I asked for. But either way: option 1 or no change, depending on Stuart's preference.

**Comment by stuartasutton** [comment]
From the beginning of the mapping work at least 4 years back, there was a
consensus that some specification would seed a spine that would serve as
the intermediary to which all other DSO specifications would be mapped.
There were discussions and a consensus that the approach to be taken would
be to pick the most verbose specification in the set to be mapped as the
initial points of mapping--so, the spine and the specification that seeds
it were then considered the same "thing".

Then, the notion of "base" entered the conversation when the synthetic
spine (synthetic intermediary) was conceived as a separate thing from any
of the specifications embodied in it.  *It was this separation that
apparently was not clear to everyone*. So the spine grows as (synthetic)
properties are added to it through the mapping process.   To the DSOs and
the Agents mapping, these notions of base and synthetic spine are
*irrelevant*--all they need to know is that they are mapping their
specification to this thing--this synthetic, evolving schema--that grows as
the mapping progresses. After a mapping of a couple of specifications, the
synthetic spine is nothing but a master list of properties representing all
the attributes in the specifications that have been mapped so far.  *There
is absolutely no real or defensible reason that the source schema for
specific properties in the synthetic spine are even publicly
identified *(although
obviously important to the application's functioning)!

In sum, with the synthetic spine as a separate entity, even the schema that
seeded it (i.e., the Base) would have an exact match on its properties to
its properties in the synthetic spine as the diagram below indicates.

[image: Mapping Flow-Full Spine_No Match.drawio.png]

So, my take is that given a set of schemas to be crosswalked, machine pick
(possibly with human override) the most verbose specification and seed the
Synthetic Spine.

**Comment by stuartasutton** [comment]
From the beginning of the mapping work at least 4 years back, there was a consensus that some specification would seed a spine that would serve as the intermediary to which all other DSO specifications would be mapped. There were discussions and a consensus that the approach to be taken would be to pick the most verbose specification in the set to be mapped as the initial points of mapping--so, the spine and the specification that seeds it were then considered the same "thing".

Then, the notion of "base" entered the conversation when the synthetic spine (synthetic intermediary) was conceived as a separate thing from any of the specifications embodied in it. **It was this separation that apparently was not clear to everyone**. So the spine grows as (synthetic) properties are added to it through the mapping process. 

To the DSOs and the Agents mapping, these notions of base and synthetic spine are **irrelevant**--all they need to know is that they are mapping their specification to this thing--this synthetic, intermediary, evolving schema--that grows as the mapping progresses. After a mapping of a couple of specifications, the synthetic spine is nothing but a master list of properties representing all the attributes in the specifications that have been mapped so far. **There is absolutely no real or defensible reason that the source schema for specific properties in the synthetic spine are even identified in the mapping interface** (although obviously important to the application's functioning)!

In sum, with the synthetic spine as a separate entity, even the schema that seeded it (i.e., the base) would have an exact match on its properties to its properties in the synthetic spine as the diagram below indicates.

![Mapping Flow-Full Spine_No Match drawio](https://user-images.githubusercontent.com/2939046/143908292-483c79b4-316f-46d0-b350-674c8470988a.png)


So, my take is that given a set of schemas to be crosswalked, machine pick (possibly with human override) the most verbose specification and seed the synthetic spine during the configuration. If it eases concerns, don't identify the source of any of the terms in the synthetic spine, and automatically map the base schema as exact matches to their proxy in the synthetic spine (i.e., interpret the diagram above literally).

**Comment by richard0000** [comment]
# Technical Proposal
- Create a Spine entity when a schema file is associated with an abstract class, as a copy of the schema file.
- Show the spine in the mapping phase (not the original specification as it is now). With this, different mappings could collaborate at the “same time“.
- Update the spine each time the mapping is updated (hard one).
- Update the mappings list to take info from the different spines (new entity)
- Enhance the UI of the mappings list view to properly handle multiple abstract classes and CP’s.

@stuartasutton @philbarker @jeannekitchens  comments?

**Comment by philbarker** [comment]
1. needs a little more clarification. There should be a distinct step of deciding which schema file is used. Yes, this can only happen when at least one schema file is associated with an abstract class, but it shouldn'e happen automatically as soon as there is aschema file associated.
2. yes
3. Updates are only needed when new terms are added (what Staurt calls the synthetic terms), not each time any mapping is made.
4. I don't understand, probably because I don't know what the mapping list is.

**Comment by stuartasutton** [comment]
Phil is correct as to num. 3, the only signals needing to be sent is when there is a new synthetic term added to the spine. I also don't understand num. 4.  Is that the list on the opening screen that shows the different configuration profiles?

**Comment by richard0000** [comment]
@stuartasutton @philbarker 
3. means to store the changes when a mapper saves to continue mapping later. These changes were saved only in the mapping entity. Now we will need to store it in the spine if needed so changes on it can be seen by another mappers.
4. Is about the view called "Synthetic Spine Property Mapping by Category". This one:
![image](https://user-images.githubusercontent.com/6996951/147476460-75c331f3-b8dc-4d75-bcc3-30afa5035d30.png)

Please let me know if this is fine with you.

**Comment by stuartasutton** [comment]
@richard0000, @philbarker:

OK on num. 3.  

As for num. 4, I am uncertain why we are needing **anything new** in terms of displaying mappings just because we've turned the spine into an entity.  What the real take away for the viewer of a mapping is the inferred relationships between two or more properties in real (i.e., not spine) properties. For example, viewers would not likely be interested in the mapping of any one schema to the spine since the spine is nothing more than an intermediary abstract schema. This is so true that you can imagine a display where the viewer doesn't see the intermediary (spine) at all (although they would loose the meaning of the mapping predicates if the spine wasn't present). The viewer's real goal is to see how this property in PESC aligns to that property in HR Open.  They likely don't  care at all about some abstract schema that was used to reveal the alignment beyond what the spine property might add to their understanding.

Anyway, before making the spine an actual entity, it was displayed in the far left column--that remains true. The only real change for the viewer, is that the schema selected to seed the spine does not get's lost in the first column since every actual schema--including what I've been calling the "base" or "seed"--are now mapped to the spine. What I mean by this is that in the current version, if CEDS (or any other of the schemas to be mapped) is elected as the base, CEDS does not show up as one of the schemas being mapped to the base. When we are finished with these changes, if CEDS were selected to seed the spine, it nevertheless also has a column along with the other schemas to be mapped to the spine (with exact match to the properties it contributed to the spine as the base schema).

**Comment by jbaird123** [comment]
Resolved
