### ISSUE TITLE
Improve tests performance

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#154]
# Description
There are some tests related to fetch specifications, vocabularies from the internet, taking more time than expected. The performance was improved in one of the commits in [this PR](https://github.com/learningtapestry/desm/pull/2). Then the latest commits in it made it come down again.

# Notes

1. Its using VCR cassettes to avoid hitting the internet repeated times.
2. It's inferring the type of file based on the content of the HTTP response from the provided url. This could be avoided if we add the possibility of specify that. Both from the UI and the backend.
3. The configuration profile tests takes time because it tests activating it, many time, and this triggers all the creation logic.

**Comment by stuartasutton** [comment]
@richard0000 and @philbarker, as for bullet #3 (file type), I don't see any need for having to infer the file type.  Since we only process a limited set of schemas--CSV, XML Schema, JSON Schema, RDF Schema (JSON-LD)-- we can provide a dropdown pick list and require a selection on data entry.

**Comment by richard0000** [comment]
@stuartasutton that would be great. Only if that would mean getting rid of type inferring on all places (mapper view - upload, all CP creation/edition views).

This change would mean several changes in the code, but will alleviate the tests and the overall performance of parsing files across the platform.

Please confirm, thanks.

**Comment by stuartasutton** [comment]
I think we should do it (drop-down menu with the acceptable schema). Weren't there dropdown indicators in the first wireframes I created that launched the configuration profile work? I believe there were. 

Phil?

**Comment by philbarker** [comment]
I think inferring is complicated, e.g. a JSON file could be be a JSON Schema or a RDF Schema; and RDF Schema could be in JSON or turtle or even XML (assuming we accept turtle and RDF/XML, maybe we don't).  Not all webservers are properly configured to handle this. So I would go for setting these explicitly.

**Comment by richard0000** [comment]
Already targeted in #172
