### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#160]
I don't know if it helps anyone here with anything, but I have created a first-cut example of a [mapping](https://gist.github.com/philbarker/d7912694baa62a0ef6d87475f040fcb4) using the DESM schema. It's in ttl, because that's easier for humans; without a context file to point to the JSON-LD is pretty brutal. Like I say, it's first-cut so let me know if you spot errors.

**Comment by stuartasutton** [comment]
Thanks, Phil. It will be helpful. Will check your example later today against the model using this graph rendering.

![Phil-Example](https://user-images.githubusercontent.com/2939046/146209836-5516e024-4446-4263-a5dc-261fe40861f4.png)

**Comment by stuartasutton** [comment]
Phil, as to your https://github.com/t3-innovation-network/desm/issues/150#issuecomment-994854287 "I found myself wanting to say what the abstract domain of a spine term is, but not really the range"--wouldn't this be solved by also adding an`rdfs:domain` arc from `rdf:Property`to `skos:Concept`?

**Comment by philbarker** [comment]
Here's another, simplified view of the entities only. And I am already noticing a couple of things missing or odd
![Untitled](https://user-images.githubusercontent.com/658047/146213666-cfac3a64-3260-4ddd-b9e0-241475c83a96.png)
.

**Comment by philbarker** [comment]
> Phil, as to your #150 (comment) "I found myself wanting to say what the abstract domain of a spine term is, but not really the range"--wouldn't this be solved by also adding an rdfs:domain arc from rdf:Property to skos:Concept?

Yes, that is what I have in the example.

**Comment by stuartasutton** [comment]
Easily fixed by adding rdfs:domain arc! 

Unless I am misreading, your simplified entity-only diagram should map exactly to the machine generated graph in https://github.com/t3-innovation-network/desm/issues/160#issuecomment-994879881. Correct?

**Comment by philbarker** [comment]
> Easily fixed by adding rdfs:domain arc!
Thank you!

> your simplified entity-only diagram should map exactly to the machine generated graph in #160 (comment) above. Correct?
Yes. It's generated by importing the example instance into GraphDB. The labels used on the nodes are auto generated and some aren't immediately obvious, but terms = CTDL terms; element = CEDS elements, org = CEDS

**Comment by philbarker** [comment]
I've added this to the gist: a SPARQL query that will pull out pairs of properties that have a good match between them. Probably needs to be tested on more extensive data

```
PREFIX : <http://example.local/>       # the "home" for this mapping
PREFIX spine: <http://example.local/spine/> 
PREFIX pred: <http://example.local/concepts/mappingPredicates#> 
PREFIX abcl: <http://example.local/concepts/abstractClasses#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX dct: <http://purl.org/dc/terms/> 
PREFIX desm: <http://desm.local/>         # to do: get real URI
PREFIX ceds: <https://ceds.ed.gov/element/> 
PREFIX ceterms: <https://purl.org/ctdl/terms/> 


select ?term ?otherTerm
where { 
    values ?match { pred:001 pred:002 }
    values ?match2 { pred:001 pred:002 }
    ?term desm:inSchema ceds: .
    ?term desm:hasTermMapping [
        desm:mappingPredicate ?match ;
        desm:spineTerm [
           	desm:hasTermMapping [
        		desm:mappingPredicate ?match2 ;
        		desm:mappedTerm ?otherTerm ;
        		desm:mappedTerm [ desm:inSchema ceterms: ]
    	    ]
    	]
    ] .
} 
```

**Comment by philbarker** [comment]
Closing this, I think it has served its pupose
