### ISSUE TITLE
CSV Uploads

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#183]
CEDS is just one schema that has a CSV format for classes, properties, and vocabularies.  This file is a CEDS CSV https://raw.githubusercontent.com/t3-innovation-network/desm/main/spec/fixtures/ceds.csv.  

Is this the entire CEDS Schema?  If so, it doesn't make sense to upload it.  CEDs has options to select select from a domain.  For example competency via this page https://ceds.ed.gov/CEDSDownloads.aspx?v=10.

However, the column are not identical between these two spreadsheets.  Of the columns in the header row, need to know exactly what's ignored and what headings are used/stored in DESM.  
[CEDSCompetencyDownloadElements.xlsx](https://github.com/t3-innovation-network/desm/files/8507201/CEDSCompetencyDownloadElements.xlsx)

The entire file or only selected domains are downloaded from this page https://ceds.ed.gov/CEDSDownloads.aspx?v=10
![image](https://user-images.githubusercontent.com/20917206/163851595-a6f31fa1-fa22-473a-bab0-38b0e8d517a2.png)

1. Need listing of column header rows that are required.
2. Need to be able to reuse the header row with instructions so other schemas that use CSV to upload know the required format.
3. With CEDS the Competency download file that I link has column call Option Sets.  Those are vocabularies.  Are those uploaded directly via this file and stored as individual concepts?

I need to be able to do a simple test mapping focused on Competency Framework and Competency so need to be able to upload CTDL ASN as JSON, CEDS as CSV and make up a sample schema via a spreadsheet using the standardized header row.

**Comment by excelsior** [comment]
@jeannekitchens The CEDS file from our repository seems to contain the entire schema. However, it's meant to be used in our automated tests, we don't have to upload it in production.

1. The required columns are:

- `Entity`
- `Global ID`
- `Element Name`

The `Option Set` column is optional, but if it has actual values, then the `Technical Name` column is also required. The `Definition` column is optional. The rest aren't used at all.

However, the latest versions of CEDS files don't contain the `Entity` column, which we use for generating property IDs. I believe, we'll need to revisit this mechanism to not rely on the absent column.

2. Yes, any CSV with the above columns present should meet this format.

3. Yes, options sets get converted into concept schemes and concepts.

**Comment by excelsior** [comment]
@jeannekitchens According to the [design doc](https://docs.google.com/document/d/1tmiCsCvie350l55JTE4w4K3sYdIAk84xXBQnyGyG_QA/edit#heading=h.wed9mm4kn3bd), the definitions get converted into `rdfs:comment` instances which are optional as per the [RDF spec](https://www.w3.org/TR/rdf-schema/#ch_comment) (or at least that's how I interpreted it when implementing the converter).

But we can make it required, it'd be a small change.

**Comment by jbaird123** [comment]
CSV Upload file definition and sample can be found here:  https://docs.google.com/spreadsheets/d/1YXD6wAnpzoWxsv2aw9zrzTY6NmLwmKB-KmmfQMd0Ftw/edit#gid=0
