### ISSUE TITLE
Uploading multiple schema files for a single entity mapping

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#2]
When an SDO uploads schema for a specific entity mapping--e.g., `Organization`, that nearly always involves uploading multiple files. For example when HR Open uploads its files to describe an `Organization`, its primary file is `OrganizationType`. But, the primary file also references other entities necessary to a complete description. For example, the `OrganizationType` schema has a `contacts` property that references a `SpecificPersonType` entity as well as a `taxId` property that references an `IdentifierType` entity. Thus, in this brief example, HR Open needs to upload the following schemas to do an `Organization` mapping:

>`OrganizationType.json`
`SpecificPersonType.json`
`IdentifierType.json`

To get a better sense of the extent of this schema-as-lego-set, see the HR Open files for `Organization` mapping at https://drive.google.com/drive/u/0/folders/1yAAL7Cggqy5rSX_8gsslTeQ9jjMSAjmd.

**Comment by philbarker** [comment]
(I was just discussing this with @jbaird123 ) 

Looking at the HR Open Organization example, there are links from the primary files to the required parts. Trouble is that 
1) these are relative directory links, and as they have been uploaded to the a directory structure that reflects the domains used by the mapping project, the required files are not in the expected locations. For example, `OrganizationType.json` has the link 
```
"taxId": {
[...]
            "$ref": "../base/IdentifierType.json#"
```
but the file `IdentifierType.json#` is actually in the folder `../` not `../base/`

2) in general, how would the developer know which file to start with? --this wouldn't be an issue for an actually user of the tool who we assume would know their spec, but it is for the developer.

So, I think what @jbaird123 needs are the relevant HROpen specs as published by HROpen and a list of which are the best starting points for each of the mapping project domains.
