### ISSUE TITLE
Automatically add all selected elements to new spine

### ISSUE THREAD

**Issue by jbaird123** [t3-innovation-network/desm#217]
When a user uploads a specification for a new spine, all elements selected in the Domain Mapping section (step 2) should automatically be added to the spine (left side of the screen).  The attached image shows that 6 properties were selected in step 2, but none of them have been added.  Because the spine is new, there are no elements in it, so all 6 should automatically be added and mapped with the closest match (in this case "Identical").  It is also worth pointing out that the two terms "description" and "name" have been added automatically, but I don't know where those came from.  I think they should not be there.  

![image](https://user-images.githubusercontent.com/2940423/179310844-81c0ef46-2f12-4398-bd6f-35a6318e4d02.png)

**Comment by jbaird123** [comment]
@excelsior - the new elements are correctly added on the left, but they also need to be created automatically on the right.

**Comment by excelsior** [comment]
@jbaird123 Done.
