### ISSUE TITLE
Deleting a spine with existing mapping throws uninformative error

### ISSUE THREAD

**Issue by jbaird123** [t3-innovation-network/desm#223]
The error message below gets displayed which is fairly useless.  Instead, it should display a message stating "Cannot remove a spine with existing mappings. Please remove all mappings before removing the spine."

![image](https://user-images.githubusercontent.com/2940423/180020274-810bbea7-a54c-4cbd-806d-00422b4d6f55.png)

**Comment by excelsior** [comment]
@jbaird123 I changed the error message and also fixed a couple of deletion related bugs I found.
