### ISSUE TITLE
List of classes with spine is not accurate

### ISSUE THREAD

**Issue by jbaird123** [t3-innovation-network/desm#224]
I removed all mappings and spines from the "Joe Test 12" profile, but when I went to upload a new specification, the list of classes still had some classes marked green indicating that there was a spine already associated with the class.

![image](https://user-images.githubusercontent.com/2940423/180021006-0df12ae2-4acb-49ad-b1f0-e27d4b598f5f.png)

**Comment by excelsior** [comment]
@jbaird123 This issue has been resolved by #222 and #223 fixes.
