### ISSUE TITLE
Reset Password button disabled

### ISSUE THREAD

**Issue by jbaird123** [t3-innovation-network/desm#237]
After typing in a new password, the "reset password" button is disabled.

![image](https://user-images.githubusercontent.com/2940423/180850929-27decdcd-3596-47a9-81b0-5df97fe383df.png)

**Comment by jbaird123** [comment]
@excelsior  - This is still an issue, and it seems to be caused by the presence of the LastPass icons that appear in the fields.  When I disable LastPass, the issue goes away.  Please see the image below to see the icons I'm referring to.

![image](https://user-images.githubusercontent.com/2940423/181825676-0707e165-e8ba-4d7f-aec0-1945517d110c.png)

**Comment by excelsior** [comment]
I 'resolved' this bug by enabling the button by default. Since the password gets validates on the back-end anyway, we don't really need client-side validation.

**Comment by jbaird123** [comment]
@excelsior - The backend validation is now throwing this error even though my password meets the requirements:

Attention!
Attention: Validation failed: Password is too weak . We were not able to reset your password.

Since there is no indication of password strength displayed to the user, can we remove that validation?

**Comment by excelsior** [comment]
@jbaird123 The strength validation has been removed.
