### ISSUE TITLE
RDF file does not find any properties on import

### ISSUE THREAD

**Issue by jbaird123** [t3-innovation-network/desm#245]
The importer cannot find any properties when importing.

[dwcterms.zip](https://github.com/t3-innovation-network/desm/files/9226982/dwcterms.zip)

**Comment by excelsior** [comment]
We filter terms by the `rdfs:domain` and `rdfs:range` properties. The terms in this particular file reference domain classes via another property, `dwcattributes:organizedInClass`. Hence no properties are found for the domains you selected. I can enable filtering by that property as well. Let me know if you have a better solution in mind.

**Comment by jbaird123** [comment]
@philbarker - I would appreciate your feedback on this.  Do you have any suggestions?

**Comment by stuartasutton** [comment]
@jbaird123 & @excelsior,  what RDF file are you looking at that uses dwattributes:organizedInClass?  Please, I'd like to see this schema.  It seems aberrant to me. 

On a slightly tangential note, looking solely for rdfs:domain and rdfs:range is a bit narrow and should **_also_** include [schema:domainIncludes](https://schema.org/domainIncludes) and [schema:rangeIncludes](https://schema.org/rangeIncludes).  These "includes" properties are used by many (e.g., Credential Engine) where they are not wanting the strong semantic implications of the rdfs properties...look for both.

**Comment by jbaird123** [comment]
@stuartasutton We're using the file attached to the original message: https://github.com/t3-innovation-network/desm/files/9226982/dwcterms.zip

**Comment by stuartasutton** [comment]
Ah, Darwin Core. While this is in fact RDF, it does not adhere closely to the norms defined by RDFS for identifying the domain and range.  They don't like the formal semantics behind rdfs:domain and rdfs:range.  Schema.org did not like using rdfs:domain and rdfs:range for basically the same reason and created schema.domainIncludes and schema.rangeIncludes to soften the semantics. 

OK, in truth, DESM also does not care about the DESM formalism behind rdfs:domain and rdfs:range. Therefore, before loading, a quick and dirty search and replace could be done for dwcattributes:organizedInClass substituting rdfs:range. One thing is for sure, **DESM can't accommodate every variation like "organizedInClass" that project might think up around how they handle the notions of domain and range**. 

The most reliable filtering to isolate properties and classes is to do it on rdfs:Class and rdfs:Property. These projects (like Darwin Core), can't not use rdfs:Class and rdfs:Property and still claim their stuff is RDF.

I base my conclusion regarding dwcattributes:organizedInClass on how it is defined in the Darwin Core terms namespace: 

> "Used to organize properties within classes for easier human understanding."

and 

>"Does not imply domain or range membership in the class."

**Comment by philbarker** [comment]
I think Stuart has answered the question, the only thing I would add is that isolating classes and properties based on  rdfs:Class and rdfs:Property (and possibly in some cases owl:Class and all the owl property classes) doesn't pick out which properties are associated with which class, which can be an issue in large vocabularies.

We're going to find difficult cases, and we're going to have work around those difficulties on an ad hoc basis while hopefully gaining experience that will help us improve the tool.

Do we have a strong reason for wanting to work with Darwin Core? Can we close this issue and maybe raise a more generic (enhancement-not-bug) issue around future improvements in how finding the properties relevant to an abstract class is handled?

**Comment by jbaird123** [comment]
@stuartasutton @philbarker - I think it's fine to close this and open a new enhancement issue.  In the meantime, we need a good RDF file to test the DESM tool functionality with.  Can either of you provide one for our testing?

**Comment by stuartasutton** [comment]
@jbaird123 , I responded a few weeks back to an email(?) from you regarding RDF files to use that suggested the Credential Engine CTDL and CTDL-ASN JSON-LD files as good examples and explained how to interpret the difference between the different files available:

1. CTDL (main domains):  https://credreg.net/ctdl/schema
2. CTDL-ASN (competency domain: https://credreg.net/ctdlasn/schema

On both pages, you have download/access options in a horizontal bar. The two key differences are that both CTDL and CTDL-ASN come in two flavors: "With Meta properties" and "Without Meta Properties". The difference between the "with" and "without" is that the with includes some meta properties you would not usually find in an RDF schema file and the without strips them out.  Both flavors include any necessary concept schemes in schema files (which is also not customary, but not wrong). HOWEVER, the concept schemes are ALSO available from these pages as separate SKOS files.

I AM RESENDING THAT EARLIER EMAIL MESSAGE.

**Comment by jbaird123** [comment]
Once I had proper files, the importer works fine now.
