### ISSUE TITLE
Make Landing Page Description Editable by Admin Account Users

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#314]
The DESM landing page description of the tool, contacts etc.. needs to be editable by the admin account users.  As instances of the tool are utilized the information may need to be differ.

**Comment by philbarker** [comment]
@edgarf I don't know what is involved in this: is it just a case of documenting where the source for the landing page is deployed so that it can be edited?

**Comment by edgarf** [comment]
- [ ] Learning Tapestry will define in readme how to update the static page and also provide the contents of the static page in a specific/separate file in the repository.

**Comment by edgarf** [comment]
@philbarker , as discussed, this would just be a small paragraph on how to change the static text. Could you please review the content here and suggest any 'stylistic' or other changes if needed? Otherwise, we will "push" it into the main branch
https://github.com/t3-innovation-network/desm/pull/483/files

**Comment by philbarker** [comment]
@edgarf 
I think the file name should be `RightCol.jsx` (not .js) 

Please make it clear whether this can only be done before deployment of an instance (which seems implied by "The updates will be visible after the system is deployed") -- is it possible to change the text on the landing page after deployment?

**Comment by edgarf** [comment]
@philbarker thanks for the catch about jsx. I updated the language a bit regarding your second point. And to answer your question, the text can be changed at any point in time, the only requirement is to redeploy it afterwards.
