### ISSUE TITLE
Change tab labels "Metadata" and "Concept Schemes"

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#315]
On the config dashboard, on the screen for DSO's information when adding information about the schema being mapped, the tab labels Metadata and Concept Schemes are not very meaningful.
 
![2022-10-19 14 58 58 zebra t3-desm staging c66 me 6259455ce99a](https://user-images.githubusercontent.com/658047/196712898-795eb1b4-12e3-4514-a2c5-0229c4f33466.png)

Change "Metadata" to "Term definitions" & "Concept Schemes" to "Controlled Vocabularies"

**Comment by jbaird123** [comment]
@excelsior  - Additionally, for the time being we need to remove the "Schema Files" link altogether because there is no functionality based on the inputs from this part of the screen.  We will revisit in the future.
