### ISSUE TITLE
RDF Vocabulary without class for domain of properties

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#316]
Dublin Core Metadata Terms ([dcterms](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/2020-01-20/) is a very widely used RDF vocabulary. One reason it is so widely used is that it does not declare any class to be the domain for the properties -- so they can be used on any class. 

On importing dcterms into DESM, it does not seem possible to select properties without first selecting a class as the domain, thus most dcterms properties cannot be imported. => we need a way to select any property regardless of whether the file imported declares a domain for them.

**Comment by jbaird123** [comment]
@philbarker - I think this is an enhancement since this use case was never identified previously.

**Comment by jeannekitchens** [comment]
@philbarker have you tried uploading the DESM schema?

**Comment by philbarker** [comment]
@jbaird123 OK, that's fair enough.  

There is a workaround which is simply to edit the schema to add a domain to the properties.

@jeannekitchens I'm not sure what you mean by DESM schema?

**Comment by jeannekitchens** [comment]
Sorry...I meant DCMI:)

**Comment by philbarker** [comment]
Suggested solution
- [ ] for RDF vocabularies, always allow a "None - properties with no domain declared" option for the domain alongside the list of classes.
- [ ] for any vocabulary, allow an "All" option to import all properties.

**Comment by philbarker** [comment]
@excelsior relevant part of workflow is on schema upload, after inputting schema details and hitting the big red button, for this file 
https://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_terms.ttl I see

![image](https://github.com/t3-innovation-network/desm/assets/658047/6c35b0bf-7315-4d99-84d2-96689307ff60)

Most properties do not have any of those classes in their domain.

**Comment by philbarker** [comment]
Yup, this looks right and behaves as expected. Thank you.

![Image](https://github.com/t3-innovation-network/desm/assets/658047/d638e114-9ccd-4d7d-aecd-57c495030e2d)
