### ISSUE TITLE
Configuration Interface: Needs to flag issues that prevent status of "Complete"

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#319]
When filling in the DSO information, i.e., DSO organization fields and DSO agents fields, when copying and pasting email addresses and blank space is added to the end of the email addresses.  The blank spaces validation prevents the configuration from becoming "Complete" but does not show any issues via the UI. The UI needs to provide a message minimally so users know when any fields that are being validation fail.  There may be other fields as well.   @jbaird123 seems the validation is there so is not displaying error messages a bug?

**Comment by jbaird123** [comment]
@excelsior - Please add the following validation errors:

- Invalid email address (make sure to trim whitespace before validating)
- Invalid URL
- Required field is missing.
- Unexpected error - followed by the technical error encountered

**Comment by philbarker** [comment]
Per Joe's message, add specific information for when there is
- [ ]    Invalid email address (make sure to trim whitespace before validating)
- [ ]    Invalid URL
- [ ]    Required field is missing.
- [ ]    Unexpected error - followed by the technical error encountered
Also
- [ ]  Invalid or missing phone number

In all cases, please say which email / URL / field value is offending or which page the offending value is on (just don't leave us hunting through 20 config pages looking for a URL with some subtle typo in it).

**Comment by philbarker** [comment]
@shlag3n 
Why is "General description" flagged as being required? By trial and error (it didn't taker much) I found this to be "Profile Description" but it does not have a red asterisk by it and I don't think we should require it.

Likewise, why is Abstract classes Version being required?

Please look at the rest of interface and  check that the required fields are only those that are marked as such.

**Comment by shlag3n** [comment]
@philbarker fixed and deployed on staging (gopher).

**Comment by philbarker** [comment]
OK, this looks good, thank you @shlag3n Moving it to QA passed.

**Comment by AH1CEDS** [comment]
@edgarf , I am unable to QA this issue as it requires admin-level access to the DASHBOARD where an admin would add users, update their info, etc. The 2 demo/test profiles I have do not have this level of access.

**Comment by AH1CEDS** [comment]
@edgarf , I tested creating a new configuration profile on 07-15-24 using an admin account on the staging server (gopher).
1) General issues: 

-	It appears that not all Configuration Profile form’s fields are being validated. Consider restricting what info can be entered into each field and/or validate all fields. For example, I was able to enter text over 1,000 characters long into fields like the File Name under Step 2 (Select the mapping predicates) and DSO Name under Step 4 (DSO's information).

-	“Date Created” goes back in time as the form is being completed and a user moves from one step to another. For example, clicking on Step 2 and then back to Step 1 moves the date back by one day. When exiting to the “Configuration Profiles” screen, the incorrect date of creation is displayed. Once the profile is re-opened for editing, “Date Created” initially resets to the correct date, but then again starts moving backwards by a day as one starts moving through the steps.

![image](https://github.com/user-attachments/assets/1520cd73-55be-452c-9b3f-9633189cfd58)
![image](https://github.com/user-attachments/assets/aa999ac7-282f-4a55-982f-fde6a060e0b6)
![image](https://github.com/user-attachments/assets/96b84363-06b8-4a3d-b162-d085bde3b96d)

-	Inconsistent behavior saving the completed profile: Upon exiting a “Complete” profile to the “Configuration Profiles” screen, the profile icon status showed “Incomplete.” Upon re-opening the profile for editing, the status remained “Incomplete” while the “Origin (URL)” on Step 2 and “DSO Email” on Step 4 became blank. After re-entering the info in those 2 fields, the status changed back to “Complete” and remained as such upon exiting to the “Configuration Profiles” screen.

-	I did not see any form fields that asked for a phone number, so I was unable to test their validation.

2) Email, URL, and required fields:

**Steps 2-3 (Select the mapping predicates, Select the abstract classes)**

-	“Origin (URL)” is marked as required field, but a blank entry does not trigger an error, either as focus leaves the field or upon clicking Previous / Next buttons.

**Step 4 (DSO’s information)**

-	“Homepage URL” and “Standards Page” fields are not marked as required, yet produce an error when left blank.
-	If either the “Standards Page” or the “Homepage URL” is blank, a single error message is displayed ("Please check the standards page and the homepage URL"). This can be confusing as the message doesn’t clarify which URL is invalid/missing.
-	“DSO Email,” “Standards Page” and the “Homepage URL” fields allowed me to paste text over 1,000 characters long and _not_ in the valid email or URL format without generating an error. 
-	Email in the _required_ “DSO Email” field had to be entered in the valid format for the profile status to become “Complete,” but invalid entries in the _non-required_ “Standards Page” and the “Homepage URL” fields did not affect the completeness status.
-	It is unclear why there are 2 separate fields with different labels, but identical input descriptions. Additionally, label “Standards Page” doesn’t specify “URL” whereas “Homepage URL” does.
![image](https://github.com/user-attachments/assets/c745c00f-7df7-4c68-bb09-c36e05fd4764)

**Comment by edgarf** [comment]
@philbarker @AH1CEDS - I feel like we should probably revise this whole list and come up with priorities on the findings here, as this most likely will take a few issues here to be solved.

**Comment by jeannekitchens** [comment]
@edgarf some of these are straight forward and are based on modern development requirements for validation.  Why not add standard validation? e.g., real URL. If something isn't required such as a phone number, which should not be required, do not make it required. @edgarf please provide the clean list and if it is outside the purpose of this issue, set up a new issue.  However, it seems the validation requests were clear. It is essential at this point to no longer delay the essential funcationality of the DESM tool.

**Comment by edgarf** [comment]
Added blank task here https://github.com/t3-innovation-network/desm/issues/565
