### ISSUE TITLE
New user password set up

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#320]
Currently the email to new users offers them the choice to "[Click here](https://zebra.t3-desm.staging.c66.me/forgot-password) to set up your password and log in." which, confusingly, goes to a reset password page, or "[Sign in!](https://zebra.t3-desm.staging.c66.me/sign-in)" which assumes they have a password.

It would be better to have a distinct page for new users to set a new password.

**Comment by DMSaunders** [comment]
Ha, Phil, you beat me to it!
Screenshot:
<img width="993" alt="Screen Shot 2022-11-02 at 7 35 05 PM" src="https://user-images.githubusercontent.com/37890092/199638223-e58fcde0-3fc2-4c6b-99fb-d50ab98f2a17.png">

**Comment by jbaird123** [comment]
Resolved
