### ISSUE TITLE
DESM Home page text could take up more screen space

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#322]
Underused real estate here could be taken up by wider text column, or another column, see https://github.com/t3-innovation-network/desm/issues/321 

![Screen Shot 2022-11-03 at 1 12 33 PM](https://user-images.githubusercontent.com/37890092/199824505-b7a50cf9-0672-424a-a1ca-c230d7c8da2b.png)

**Comment by jbaird123** [comment]
@DMSaunders - This should be handled as part of issue #311
