### ISSUE TITLE
Domain looks already checked during the upload specification page

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#323]
Usage friction. The note that domains in green have a spine uploaded is good, it would be more visible placed right below the selection boxes where the other notes that assist with form completion are for each field. Right now it looks like a note for the upload section.

The green filled-in box makes it look like it has already been selected. Suggest highlighing the domain name in green instead of the checkbox.

![Screen Shot 2022-11-03 at 1 15 48 PM](https://user-images.githubusercontent.com/37890092/199825054-4d46c0b3-31eb-4490-845d-caad2d82bf17.png)

**Comment by jbaird123** [comment]
@excelsior - Please make the changes suggested.

**Comment by jbaird123** [comment]
Resolved
