### ISSUE TITLE
Guidance for naming your mapping

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#327]
Provide guidance on naming your mapping:

- Include the purpose of this particular mapping
- You can include the name of the organization the schema is from
- 
@jeannekitchens @philbarker anything to add here?

**Comment by jbaird123** [comment]
@DMSaunders - Is the text you provided above the exact text you want added?  If not could you please provide it?

**Comment by jeannekitchens** [comment]
@jeannekitchens review the configuration set up and provide any exact text changes.
@jeannekitchens review the new mapping form and provide any exact text changes.

**Comment by 4pins** [comment]
@jeannekitchens I've been thinking roughly: [Organization]-[Standard]-[Version]-[Domain(s)]
