### ISSUE TITLE
Go back to add another domain - what does this do to the mapping

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#328]
If it turns out I needed to have selected another or a different domain, I don't see a back button.
I can go back on my browser and start over, which means reuploading and renaming

It would be useful to test to see if this causes any bugs given different points at which the process is started over

**Comment by jbaird123** [comment]
@DMSaunders - We need additional clarity on this.  There is a "Re-import" button which I think accomplishes what you're looking for.

**Comment by DMSaunders** [comment]
@jbaird123 I only see the re-import button on the first step of the process "upload specification". I do not see it on the next two steps which is where I would want the option to go back and add more domains.

**Comment by jbaird123** [comment]
@DMSaunders - This would be an enhancement which we can look at adding in the future.

**Comment by philbarker** [comment]
Re-evaluate when other work-flow related issues have been addressed.

**Comment by philbarker** [comment]
Should be addressed now
