### ISSUE TITLE
Drag and drop of properties during mapping

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#329]
Currently the drag and drop of properties into the mapping requires selecting a property first before dragging. 
In theory, I could see that being useful to be able to easily scroll through what you have already selected.
However, if it were possible to drag properties over such that they were viewable as a list of selected properties in the droppable area, this need could be resolved.
It may be helpful to observe and see if the current method offers any benefits to users. If not, switching to a more conventional drag and drop is recommended.

Additionally, improvements to the droppable area:

- It would be helpful to enlarge the droppable area for each domain. When you drag to the left, the cursor becomes a 🚫 if you're not over the small box. 

- It would be helpful if the droppable area was not grayed out because that makes it look like you cannot interact with it until something else happens, which isn't true

- because we tend to think left to right, it may be more intuitive to drag properties from the left the right of the screen

![Screen Shot 2022-11-03 at 5 16 14 PM](https://user-images.githubusercontent.com/37890092/199858661-8825f940-b897-4139-a22c-127e1dd53575.png)

**Comment by jbaird123** [comment]
Resolved.
