### ISSUE TITLE
Increase the scrollable area for viewing the mapped predicates

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#330]
Might as well use the available screen space to help users view the mapping and assign predicates, as the main purpose of the DESM tool.

**Comment by jbaird123** [comment]
@excelsior - Please increase the vertical size of this scroll window (and make it possible for the user to expand it further if necessary).

![image](https://user-images.githubusercontent.com/2940423/200871918-c3addecb-0c46-4610-b2e6-f53fb5fb3bd8.png)

**Comment by jbaird123** [comment]
changed layout
