### ISSUE TITLE
Help users understand spine creation vs spine usage

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#331]
It will be useful to provide explanation for why on the first pass, a user has to create a mapping that shows all the properties identical to themselves to create the spine. While we understand, new users will benefit from an explanation that gives them confidence that they are doing it right.
It will then also be useful to explain how the spine that they are using was created (ie by a user) and how changes to the spine are made.

**Comment by jbaird123** [comment]
@excelsior - Please add a popup message after the spine gets created to inform the user.  Message should read:  "A new spine was created, so no further mapping is necessary.  If you want to publish the mapping, please click "Done Alignment".

**Comment by DMSaunders** [comment]
Thanks Joe. Could there also be messaging for a user who encounters an existing spine to tell them who made it and that they can add to it using the add to synthetic button?
