### ISSUE TITLE
White space at bottom of screens

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#333]
White space at the bottom of the screen during mapping.
Would be useful to see what pages this affects.
This doesn't seem to impact functionality.

![Screen Shot 2022-11-03 at 6 09 25 PM](https://user-images.githubusercontent.com/37890092/199863617-15c452b1-2715-4f2b-95d1-8b0c6b3a0f36.png)

**Comment by jbaird123** [comment]
Resolved.
