### ISSUE TITLE
Control for identical mapping names

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#336]
I can name my mapping "test" as many times as I want. Since there's no way to distinguish between them now, maybe users should be barred from using the same name over and over?

![Screen Shot 2022-11-09 at 5 26 15 PM](https://user-images.githubusercontent.com/37890092/200977741-ec9cd6ec-093b-4e35-89c6-5dc4d214b3c4.png)

**Comment by philbarker** [comment]
Deal with this through guidance in #327
