### ISSUE TITLE
Long text gets cut off on property selection popup

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#337]
This is the popup in question, on a schema with longer names, we noticed that they got cut off.

![Screen Shot 2022-11-09 at 5 28 21 PM](https://user-images.githubusercontent.com/37890092/200978052-f5998b1f-da7f-4a44-81c8-868a5c16ee8a.png)

**Comment by jbaird123** [comment]
@excelsior - Please remove this popup.  It is not useful.

**Comment by jbaird123** [comment]
Resolved.
