### ISSUE TITLE
Allow admins to impersonate mappers

### ISSUE THREAD

**Issue by jbaird123** [t3-innovation-network/desm#342]
Future enhancement:  Allow Allow admins to impersonate mappers.  Without this functionality, admins need to have a separate user account for each DSO that they want to log in and view.

**Comment by stuartasutton** [comment]
+1 but for a slightly different reason. Corrections might need to be made after the mapper is no longer with the project.

**Comment by philbarker** [comment]
+1 the current approach of using separate aliases for adminning and mapping is unwieldy and seems a little buggy, for example my admin account currently shows me as Phil Barker at Schema.org even though there is nothing in my admin profile about schema.org

![image](https://user-images.githubusercontent.com/658047/202702323-235b0be5-512d-4226-bbd8-10036d623afc.png)

**Comment by philbarker** [comment]
We also have emerging a use case where someone at an organization using a system that imports data that is standard compliant wants to create a mapping from the standards they support to their own internal representation. This will likely involve one person playing all roles.

**Comment by excelsior** [comment]
To impersonate an agent, log in as an admin and navigate to the Agents section of the dashboard:

https://gopher.desm.staging.c66.me/dashboard/agents

Then click the `Impersonate` link on the right side of the agent you want to impersonate.
To stop impersonating, click the `Stop Impersonating` button in the top right corner of the page.
Clicking the `Sign Out` button will sign you out from both accounts, not only stop the impersonation.

**Comment by philbarker** [comment]
OK, this works.

For the record I DO NOT LIKE THIS SOLUTION.

It goes way further than the use case requires, which was simply that Admin users should have view and edit rights on mappings.

But it'll do until we get better access / role management in DESM.
