### ISSUE TITLE
Configuration Profile DSO tabs overlap at 100% zoom

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#343]
After adding several DSOs, the DSO tabs overlap at normal zoom.  Have to zoom out to 50% so they don't overlap. 

![image](https://user-images.githubusercontent.com/20917206/202313777-45f03ccf-5cf1-423d-ab2a-8c7032216ee4.png)

**Comment by jbaird123** [comment]
resolved.
