### ISSUE TITLE
After logging into DESM with my admin user name, nothing shows from this url https://tool.desmsolutions.org/mappings

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#348]
I'm logged in as pilot admin.  I click on View Mappings and see the wrong URL and no web page. I've seen this bug a few times now.  Also, I cannot use the back button to go back to the home page, the URL changes but no web page.  I have to referesh and re-log in. Is it intended that admins cannot see any mappings unless they login as every DSO?  If so, that doesn't make sense.  Regardless, if there's no mappings to see, the page should still render and show that there's no mappings.  

![image](https://user-images.githubusercontent.com/20917206/202764296-7911cfd7-3834-4ea3-84ab-762603bcedb4.png)

![image](https://user-images.githubusercontent.com/20917206/202764704-7937602f-59f9-4f5f-b2d0-12e362b727e0.png)

**Comment by jbaird123** [comment]
@jeannekitchens - The view mappings screen was never intended to be accessed via an admin account.  Some time back, this button was disabled for admins.  You don't have to log in as every DSO to be able to see the mappings.  If you log in as any normal user in any any DSO, you should be able to see all mappings.

**Comment by jbaird123** [comment]
@excelsior - We should disable the view mappings button for admins until we come up with a better solution (enhancement).

**Comment by jbaird123** [comment]
The blank screen is definitely a bug that needs to be fixed.

**Comment by jbaird123** [comment]
Resolved.  Button is disabled for admins.  If admins need to be able to access this, we'll need to do this as a future enhancement.
