### ISSUE TITLE
Repository folder naming and organization

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#349]
Some of the folders in the github repo could be better named, and we should think about how we separate test / example data from code. It's not at all obvious where config files are,  which files are just examples, and what the IPR and currency status of some of the examples is.

Suggestions:

- rename folder `concepts` as `ConfigOptions`. We should also make it clear that the files are examples / recommendations.
  - the `hrOpen/DisabilityLevelCodeList` folder doesn't belong with the others, it's example data.
- rename folder `examples` as `MappingOutput` and move to a `Documentation` or `Examples` folder.
- we maybe should remove the folder `desmTestSchemas`? Should we keep other people's examples somewhere else? Or are these used in testing?
- check whether `schemas` duplicates `examples` and delete or move to  `Documentation` or `Examples`.

I recognise that this is low priority, and but that we need to check that none of the folder names are used in testing or deployment, but if we agree what goes where I can make the changes.

**Comment by jbaird123** [comment]
@excelsior - Please clarify which folders are safe for others to modify without breaking the deployment and testing.

**Comment by philbarker** [comment]
fixed this a while back (albeit with some unintended consequences when rolling out updates).
