### ISSUE TITLE
View Mappings versus View Specifications - difference isn't clear

### ISSUE THREAD

**Issue by angelajubinvilleqip** [t3-innovation-network/desm#351]
The distinction between "view mappings" and  "view specifications" is not clear from this screen:
![Screen Shot 2022-11-23 at 12 35 48 PM](https://user-images.githubusercontent.com/88741604/203613424-9d780e4a-4d4e-4259-a6b1-18adcdcad770.png)

When you click on "View Specification" it takes you to a screen with the title, "Synthetic Spine Property Mapping By Category".

**Comment by jbaird123** [comment]
@jeannekitchens - The "View Mappings" screen is functionally different from the "View Specifications" screen.  View mappings allows users to see a list of mappings and click on one to edit (authentication is needed for this screen).  The "View Specifications" screen is open to the public and displays all of the details of all mappings for each domain in the configuration profile.  The change needed is trivial (label changes), but I do need clarity on exactly what labels we should use for each screen.

**Comment by jbaird123** [comment]
I agree that "View Specifications" is not a great label, but I'm not sure what to use instead.

**Comment by jeannekitchens** [comment]
If the View Specifications screen is publicly shared mapping it should say "View Shared Mappings".

**Comment by jbaird123** [comment]
Resolved.
