### ISSUE TITLE
Spine terms added but then mapped terms disappear

### ISSUE THREAD

**Issue by jgoodell2** [t3-innovation-network/desm#352]
After adding spine terms and then save. Returning to the mapping shows spine terms saved but the mapping is gone.
<img width="3077" alt="image" src="https://user-images.githubusercontent.com/6494706/203653320-3e1d2e8f-2222-4164-b90d-c3e5d41d3466.png">

**Comment by jgoodell2** [comment]
...this prevents clicking of "Done Alignment"

**Comment by jeannekitchens** [comment]
@jbaird123 @excelsior Jim is mapping CEDS.

**Comment by jbaird123** [comment]
@jgoodell2 - I'm having trouble duplicating this problem.  Can you provide exact instructions including the file you're uploading to duplicate the issue?  A screencast would be helpful if you can do it.

**Comment by jbaird123** [comment]
@excelsior - The issue here is that the elements in the screenshot above were added as synthetic elements and automatically mapped as "Identical".  After saving, the mapping was lost, but the spine term remains.  We went back in and tried to manually map the elements, and they do not get saved.

**Comment by jbaird123** [comment]
Resolved. Please reopen if the issue persists.

**Comment by jgoodell2** [comment]
Yes. I confirm that this issue is resolved.
