### ISSUE TITLE
slow to add large number of properties on "map to domains" screen

### ISSUE THREAD

**Issue by angelajubinvilleqip** [t3-innovation-network/desm#354]
On the "Map to Domains" screen, when using the "select all" function for a large number of elements/properties (we tried 709) and you're dragging, it's not obvious that it's working. You need to hold the mouse button down, drag the properties, hover over the box on the left, and then wait about 20 seconds for the box to indicate that the properties are ready to be added. Then you can release the cursor. There's no visual feedback when you drag the selected properties that it's working. You just have to wait for the box to change. 

Apologies, we did not get a screen shot/visual representation of the issue.

**Comment by dlawsonQIP** [comment]
Is this functionality going to change? It might be helpful to modify how this functionality works and add an onscreen status indicator to show that processing is occurring.

**Comment by philbarker** [comment]
Should be better (or at least different) now.,
