### ISSUE TITLE
Mapping more than one property to one in spine

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#355]
The way to map more than one property from a standard to one in spine could be more obvious (it's easy to miss, see #353 ), it's also not so easy on the user as all properties form the standard being mapped have to be added in one go.

Suggestion: don't stop further properties from being added once one has been.

This would mean that users could map several properties to one in the spine as and when they come to them while working through the list of properties in their standard.

**Updated Feb, 20**
Also update here drag behavior (moved from #374) to make possible to just drag a property over without having to first select it

**Comment by jeannekitchens** [comment]
@philbarker this goes along with the other mapping issues so I'm good with moving this to priority 1.

**Comment by philbarker** [comment]
LGTM 💯
