### ISSUE TITLE
CSV import is falsely identified as CEDS

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#358]
Importing this data
[DESM Schema Upload CSV Template - Minimal Sample (5).csv](https://github.com/t3-innovation-network/desm/files/10141362/DESM.Schema.Upload.CSV.Template.-.Minimal.Sample.5.csv)

Results in this preview
![image](https://user-images.githubusercontent.com/658047/205302111-9c880e98-f05d-4448-9d83-a92a1d279308.png)

It looks like the tool is assuming that anything in CSV is CEDS, which is shouldn't.

**Comment by excelsior** [comment]
@philbarker Yes, the only CSV format we support is CEDS, hence this behavior. 

What's the format of the file you tried to import? It has all of the CEDS columns, how is it not CEDS?

**Comment by jbaird123** [comment]
@excelsior - The format we defined for CEDS can be used by anyone regardless of whether they're from CEDS or another DSO.  The issue I'm seeing is that the word CEDS gets inserted into the JSON-LD that we generate during the upload process.

**Comment by philbarker** [comment]
@excelsior The CSV format is intended for any DSO that cannot provide a schema in one of the other formats. CEDS was just the first example of this. Other DSO can map their own schema to the same headings as used by CEDS, so long as we know which columns equate to classes, properties, definitions etc.

**Comment by 4pins** [comment]
I think I had better stop:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/10967355/205407035-5eea0925-0071-4756-b9a5-691b31b7e3a3.png">

**Comment by jeannekitchens** [comment]
@4pins the issue of the CSV upload assuming CEDS is being fixed now by @excelsior.  Sorry you weren't aware of this. @excelsior @jbaird123 please let @4pins know as soon as it's safe to upload the CSV template for the A4L schema.

**Comment by 4pins** [comment]
I think this will be the quickest way to move forward.  I await word.  Thanks!

**Comment by jbaird123** [comment]
Resolved. Please reopen if the issue persists.
