### ISSUE TITLE
Removing a property having previously selected it for during domain mapping

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#361]
There should be a way after successfully loading a schema, selecting properties during the domain mapping and dragging them to the left to remove a property that was mistakenly selected.

**Comment by jbaird123** [comment]
@stuartasutton - This functionality already exists; however, there is an issue with it in that if you have previously mapped properties, those mappings get lost when you add or remove properties to a domain after the initial file upload.  To add or remove properties after the initial upload and domain mapping, follow these steps:

1. Navigate to the "View Mappings" screen.
2. Locate the mapping that needs to have properties added or removed.
3. The status of that mapping should be either "Uploaded", "In Progress" or "Mapped".  The only way to add or remove a property from a mapping is to set the status to "Uploaded".  To do this, click the ![image](https://user-images.githubusercontent.com/2940423/208547265-a0eae7f1-6425-4af2-a23e-63b50f57fd84.png) button to change the state to the prior one.  (If the status is "Mapped", it will be changed to "In Progress" and you will need to click it a second time to revert the status to "Uploaded".
4. Once the status is "Uploaded", click the ![image](https://user-images.githubusercontent.com/2940423/208548069-f7b1e92e-7e62-49ed-8719-19172725b008.png) button to return to the domain mapping screen. Once there, you can drag properties that were previously missed onto the left side of the screen.
5. To remove a property, find the property on the right side of the screen (it will be grayed out) and click the "x" in the top left of the card: 
![image](https://user-images.githubusercontent.com/2940423/208548310-98723101-a3ab-429f-afe1-28e5591ccd35.png)

**Comment by jbaird123** [comment]
@excelsior - I'm flagging this as a bug because property mappings (from the alignment mapping screen) get lost when the user follows the instructions above.  This is clearly problematic and needs to be resolved.

**Comment by jbaird123** [comment]
Resolved
