### ISSUE TITLE
Display of property label inadequate

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#362]
Currently, the human readable label for a property is used to identify properties to be mapped instead of (or in addition to) the actual property name. This assumes that the label and the property name appended to the namespace are the same. That's a mistaken assumption. For example, Dublin Core has a "created" property that has the label "Date Created". Others in ASN: "valid" with a label of "Date Valid" and the "altStatementLabel" property with "Alternative Statement Label". You need to add the property name immediately below the label or at least do so when the property name and the label are not the same since people with any familiarity with the schemas will be looking for the property name.

**Comment by jbaird123** [comment]
@stuartasutton - Just to confirm.  In the following example:

`{
            "@id": "dcterms:valid",
            "@type": "rdf:Property",
            "rdfs:comment": {"en-US": "Date (often a range) of validity of a resource."},
            "rdfs:domain": "asn:StandardDocument",
            "rdfs:isDefinedBy": "dcterms:",
            "rdfs:label": {"en-US": "Date Valid"},
            "rdfs:range": "rdfs:Literal"
        }`

You want us to display both the @id value and the rdfs:label value - correct?

**Comment by stuartasutton** [comment]
Yes, leaving the rdfs:label as primary is OK as long as the @id is below the label or in close proximity.

**Comment by jbaird123** [comment]
Resolved.
