### ISSUE TITLE
Provide alpha-ordered spine properties regardless of case

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#364]
The spine properties are in case-dependent alphabetical order on label.  Not all schemas will consistently upper-case the first letter of their label words meaning that when mixed with those that do uppercase first letters splits the display ordering into two separate arrays placing all properties with uppercased labels first followed by properties with lowercased labels. The alpha order of spine properties should be **case insensitive**.

**Comment by jeannekitchens** [comment]
@jbaird123 casing shouldn't impact the ability to order properties in alphabetical order.  This should be corrected.

**Comment by jbaird123** [comment]
@excelsior

**Comment by jbaird123** [comment]
@excelsior - Sort all alphabetically regardless of case or synthetic status.

**Comment by jbaird123** [comment]
Resolved
