### ISSUE TITLE
Fields in the Output Explainer need to be present on the Edit Page

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#37]
@jbaird123, @richard0000 & @philbarker, the data fields in the wireframes for the "[Edit Page](https://marvelapp.com/prototype/adf7283/screen/68479195)" should fully cover the properties as set out in Phil's "[Output Explainer](https://docs.google.com/document/d/1yR4LYHCD6vRbzE8njQaNw8JkIk0QVHUVRFZeLVPUB-c/edit#heading=h.i4gac9blm15p)", the [RDF schema](https://github.com/t3-innovation-network/desm/blob/master/ns/desmTerms.json), and [domain model](https://github.com/t3-innovation-network/desm/blob/master/ns/Domain_Model-REV.png). Currently the fields in the "[Edit Page](https://marvelapp.com/prototype/adf7283/screen/68479195)" wireframe **do not** fully align with the "[Output Explainer](https://docs.google.com/document/d/1yR4LYHCD6vRbzE8njQaNw8JkIk0QVHUVRFZeLVPUB-c/edit#heading=h.i4gac9blm15p)"--two properties are missing and some need relabeling.  I think that all data necessary to generate a property description in the "[Output Explainer](https://docs.google.com/document/d/1yR4LYHCD6vRbzE8njQaNw8JkIk0QVHUVRFZeLVPUB-c/edit#heading=h.i4gac9blm15p)" need to be here in the "[Edit Page](https://marvelapp.com/prototype/adf7283/screen/68479195)". **Correct?**

Notice that in the table I've used quite technical terms in form field labels--e.g., Domain, Range. I am deliberately choosing at this time to **not technically soften** these labels.

| Current Label | Revised Label |  Output Explainer |  Example Data | Notes |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| Element/Property | Property URI | rdf:Property |desm:endDate | |
|  | Source URI | desm:sourceURI |credReg:endDate |Missing property |
|  | Property Label | rdfs:label |End Date | Missing property |
| Description | Definition | rdfs:comment |"Date some event or activity ends." | |
| Class/Type | Domain | rdfs:domain |credReg:LearningOpportunityProfile| |
| Datatype | Range | rdfs:range |sdo:Date |Broadens definition |
| Vocabulary | Vocabulary | desm:valueSpace |credReg:AudienceLevel | |
| Path | XPath/JSONPath | n/a | ../../credReg:endDate  |Prompt text could be "XPath or JSONPath" |

**Comment by richard0000** [comment]
@stuartasutton in @philbarker 's [Output Explainer](https://docs.google.com/document/d/1yR4LYHCD6vRbzE8njQaNw8JkIk0QVHUVRFZeLVPUB-c/edit?pli=1), there's both range and datatype as separate attributes for a property node.

In the table above ☝️, the Datatype attribute was renamed to Range. So which value is then going to be used to fill Range?

**Comment by richard0000** [comment]
![image](https://user-images.githubusercontent.com/6996951/94447862-ab851780-0180-11eb-90fe-ac0cf847bd42.png)
So @stuartasutton  these are 3 separate fields, right? (asking because I don't see it like that in the mockups)

**Comment by stuartasutton** [comment]
Correct, those with nothing in the Current Label column are missing
properties.

**Comment by stuartasutton** [comment]
@richard0000, I have created a separate github issue #40 about dropping the desm:datatype property.

**Comment by stuartasutton** [comment]
@richard0000, above in https://github.com/t3-innovation-network/desm/issues/37#issuecomment-700056659 you ask what's in those current top three fields: Property URI, Source URI and Property Label.  Using your example of 

1. Property URI: This is the URI of the property in the DESM namespace (e.g., desm:actingAgent);
2. Source URI: This is the URI of the property in the original schema--if the property actually had a URI in the original schema (e.g., [ceterms:actingAgent](https://credreg.net/ctdl/terms/actingAgent)); and
3. Property Label: This is a human readable label for the property (e.g., "[Acting Agent](https://purl.org/ctdl/terms/AccreditAction)").

I see one more issue in the image, the value of the Domain field.  The domain of a property is the class(es) of thing to which the property may be inferred to belong (e.g., "[AccreditAction](https://purl.org/ctdl/terms/AccreditAction)"

**Comment by richard0000** [comment]
@stuartasutton so in the case of `ceterms:ActingAgent` the domain would be:
```
      "schema:domainIncludes": [
        "ceterms:AccreditAction",
        "ceterms:AdvancedStandingAction",
        "ceterms:ApproveAction",
        "ceterms:CredentialingAction",
        "ceterms:OfferAction",
        "ceterms:RecognizeAction",
        "ceterms:RegulateAction",
        "ceterms:RenewAction",
        "ceterms:RevokeAction",
        "ceterms:RightsAction"
      ],
```
correct?

**Comment by stuartasutton** [comment]
Yes, technically correct.  While it is likely that in the context of mapping, a particular domain might be what the mapper has in mind; but having the full array of domains will prove useful downstream with the RML models.

**Comment by richard0000** [comment]
Ok, so In the edit term screen, that's not likely to be a simple input... Like it is right now and in the mockups.

- Option A: Leave it like an "input", and it can be changed by the user to be (or not, depending on the user) a valid JSON array of string values.
- Option B: List the checked values as in the vocabularies, and let the array representation to be internal.

@stuartasutton thoughts?

**Comment by richard0000** [comment]
@stuartasutton I'm linking the PR #41 to get this ticket addressed. @jbaird123 FYI.

**Comment by richard0000** [comment]
Covered with PR #41
