### ISSUE TITLE
Usability and Accessibility: Change Button Text 

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#370]
From @siuc-nate

This button can be tabbed to once it appears, but it should probably say either "Done with Selection" or "Done Selecting". There are other accessibility issues, but for the sake of time I'll skip over them.

![image](https://user-images.githubusercontent.com/20917206/206203946-22dcd968-a6d8-44d3-a08e-4f81536a6603.png)

**Comment by jbaird123** [comment]
Resolved.
