### ISSUE TITLE
Edit Term UI Issues

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#372]
From @siuc-nate

On this screen:
- Why would you edit a property to begin with? That seems dangerous, since it would mean you are no longer aligning the original property from the original schema, but something new and bespoke instead
- The selections on the left seem a bit backwards (and I didn't indicate that any class other than Organization should be included, so where is it getting Apprenticeship Certificate from?)
- The list where you can select a vocabulary needs to be much taller, and should probably just be its own column
- Would it be better to upload concept schemes as a separate step entirely, so they can all be done at once?
- Why do concept schemes from other sources show as options?
- Does this tool properly handle connections that have indirection (e.g. agentSectorType -> CredentialAlignmentObject -> targetNode -> Concept)?
- Changes to the label here are not reflected in the main window after clicking "Save and Exit"
- I really wish some equivalent to our meta:targetConceptScheme property existed in RDF
![image](https://user-images.githubusercontent.com/20917206/206204879-75e271c0-7beb-4bbc-8e61-0db9a08e11a8.png)

**Comment by jeannekitchens** [comment]
@jbaird123 @philbarker I bolded three of the above bullets that come across as bugs not enhancments.  The main concern is with the first bolded bullet, is the data saving correctly?  We need to look more closely at this issue. I don't recall it ever being discussed.

**Comment by philbarker** [comment]
@jeannekitchens I don't see any bold bullets

**Comment by philbarker** [comment]
Addressed with #433
