### ISSUE TITLE
Mapping UI Usability and Guidance Issues

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#375]
From Nate Argo.

How would you map properties where the data is not in the immediate class, but a few layers deep?
For example, the value for this property ("Electronic Mail AddressType") would be in Organization > address > Place > targetContactPoint > ContactPoint > contactType.
It looks like "Transformed" is the best fit, but I didn't realize the comment functionality mentioned in the documentation existed until later (see next note).

![image](https://user-images.githubusercontent.com/20917206/206207618-b04b3cfd-96b6-4de3-8aaf-daef13450725.png)

**Comment by philbarker** [comment]
In general yes, it would be as a transformation.
