### ISSUE TITLE
Editing Alignment UI Usability Issues

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#377]
From @siuc-nate

Why does "Edit"-ing an alignment result in this window instead of just letting me pick a different alignment? (It appears this is how a comment is added/edited when you select that option, but this seems very clunky. I suggest cutting out the wasted whitespace and adding a text box somewhere).
Also, the alignment list overflows the window, so you have to scroll the window to see the rest.

![image](https://user-images.githubusercontent.com/20917206/206208899-5d21586a-23e5-4bcd-8907-4319096d5889.png)

**Comment by philbarker** [comment]
UI has changed since this issue was raised
