### ISSUE TITLE
Mapping UI Usability Issues: Predicates

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#378]
From @siuc-nate

Clicking on a drop-down list causes the list of options (which has a much narrower width) to appear above the box and animate downwards. I assume the intended animation here was to have it show up behind (and be cropped by) the box?

![image](https://user-images.githubusercontent.com/20917206/206209354-e72a24f6-85e8-49c0-9410-90509e2ac433.png)

**Comment by philbarker** [comment]
I think this is personal preference not a bug, I like how it is. Anyway, it'll likely change when other features come in around alignment. Making priority 3.

**Comment by philbarker** [comment]
UI has changed since this was raised
