### ISSUE TITLE
URLS do not work

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#379]
From @siuc-nate

The markdown-style links don't appear to work (perhaps they aren't meant to?).  It would be very important for these to have a target of "_blank" if they did work though!

![image](https://user-images.githubusercontent.com/20917206/206209682-a4be4bcb-3888-4c97-9a62-e8bd17fb3020.png)

**Comment by philbarker** [comment]
I don't think we should worry too much about other people's formatting. I don't think this happens a lot. Seems low priority, setting to 3.

**Comment by philbarker** [comment]
Fixed (we think)
