### ISSUE TITLE
Search functionality on the Edit Page

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#38]
@richard0000 & @jbaird123, in yesterday's demo, you demonstrated searches of the data in the "Raw" window of the [Edit Page](https://marvelapp.com/prototype/adf7283/screen/68479195) by entering your search term in the Data Type field. This is rather non-intuitive.  Since there will be some work on this page as a result of issue #37, why not put all of the data entry fields on the left of the Raw frame and use the space above the Raw frame now occupied by Data Type as a well labeled search box?  Also, please change the descending order of the fields to match the descending order in the issue #37 table.

**Comment by richard0000** [comment]
@stuartasutton the input field above the raw window is not a search box. It's the input to view and/or edit the "Datatype" of the Property being edited.

What I presented for it, is just that when you type in the Datatype input (and in any of the other inputs, not only this), the raw window will reflect the change. Please take a look at the image below for an example:
![live-edit-raw](https://user-images.githubusercontent.com/6996951/94182185-f9470a80-fe76-11ea-9ead-c54587eaae8b.gif)

If you're ok, this issue can be closed.

**Comment by stuartasutton** [comment]
@richard0000, sorry, I was confused about the search bit. 

I'd like to leave the issue open for some further clarification.  I have a couple of questions about the data I am seeing in the Raw panel:

1. Is what we are seeing in the Raw panel our internal representation of the source data for CredentialPerson (an rdfs:Class) in CTDL?
2. There is a property called "domain" where you have listed the properties that may be inferred to belong to CredentialPerson (e.g., ceterms:affiliation, ceterms:approvedBy...etc.); how were those derived algorithmically from the CTDL schema?

I want to walk through the process slowly with you first uploading the CTDL schema as spine and the Schema.org as the mapped schema.  The reason is that I am a little confused by what I am seeing in the Raw panel and would like to go over it with you with a slower, more targeted demo: (1) Load Schema.org as spine, and (2) load CTDL as the mapped schema..
