### ISSUE TITLE
Mapping UI Issue: No Match 

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#380]
From @siuc-nate

The tool does not seem to differentiate between no mapping being assigned and an explicit assertion of "No Match":

![image](https://user-images.githubusercontent.com/20917206/206210162-54767166-c28b-4ad0-be5e-ee789f38949d.png)

**Comment by philbarker** [comment]
Assigned to me to check whether this is still the case.

Making priority 2 as "no match" is a sensible default (though not showing it may arguably be better)

**Comment by philbarker** [comment]
UI has changed since this was raised
