### ISSUE TITLE
Mapping UI and Guidance Issue: Assigning more than one property to a spine

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#381]
From @siuc-nate .

There does not appear to be any way to assign more than one mapping to a spine property.
For example, the spine's "identifier" is an exact match with our "identifier" property, but it is also a super-property of "CTID" (among others).  But I can't indicate that in this UI:

![image](https://user-images.githubusercontent.com/20917206/206210544-070ab37c-57f5-48af-93e6-2356c519a155.png)

**Comment by edgarf** [comment]
@philbarker I assume, that at least for now, the scope is just around documenting how to properly map multiple properties, right?

**Comment by philbarker** [comment]
@edgarf yes, I think that is a fair assumption.
