### ISSUE TITLE
Use Case URL Guidance Needed 

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#383]
From @siuc-nate 

Is this meant to be a link to the schema terms page, or something else?  "Use Case" is not a clear enough label

![image](https://user-images.githubusercontent.com/20917206/206211877-b3a455b4-a2d6-42ab-9d1a-80c3791ecef2.png)

**Comment by philbarker** [comment]
@stuartasutton do you recall why the Use Case URL box was added? I don't think we have ever used it, and I am minded to suggest it be removed unless there is a good reason to keep it.

**Comment by stuartasutton** [comment]
No, I don't recall the reason. I think it was added by Jeanne to very early wireframes. Personally, I'd delete it.

**Comment by jeannekitchens** [comment]
@philbarker @stuartasutton I'd delete it too.

**Comment by jeannekitchens** [comment]
@stuartasutton this is a good point. I suggest the configuration should have a scoping description and provide an option to link to planning documentation and the scoping needs to be displayed on the public page and part of the descriptive data.  The scoping is much clearer than referring to use cases and essential in framing and confining a mapping.

**Comment by dlawsonQIP** [comment]
Last week, we discussed that "Use Case URL" might not be needed as part of the steps to upload a specification.

**Comment by philbarker** [comment]
Suggested resolution
- [ ]  remove the Use case URL field from the interface.
