### ISSUE TITLE
Usability: Unable to go back to the properties screen

### ISSUE THREAD

**Issue by siuc-nate** [t3-innovation-network/desm#384]
Once the user has advanced to step 3, there does not appear to be any way to go back to step 2 to select, edit, etc., any of the properties.

![image](https://user-images.githubusercontent.com/21346519/206319971-a7dea3c7-8dfc-41e6-9f6e-30cbf7e6448e.png)

**Comment by jbaird123** [comment]
This functionality can be accomplished by changing the status of the mapping on the "View Mappings" screen.  Admittedly this is a bit cumbersome, but the application is functioning according to spec at this point.  We can address this in a future phase.

**Comment by philbarker** [comment]
We have a work around which we should document. Needs review of workflow and new functionality before we can action this.
Adding documentation tag and making priority 2

**Comment by philbarker** [comment]
Fixed now
