### ISSUE TITLE
Cannot add properties to synthetic spine

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#387]
When logged in as my ASN alias, when I click on "add synthetic" during property mapping, 

![image](https://user-images.githubusercontent.com/658047/207040980-3bbb062d-7ee1-4127-9e4a-50104f376ab0.png)

I get nothing but a blank screen.

Have reproduce on staging server with different schema.

**Comment by 4pins** [comment]
FYI:  I've encountered a blank screen, seemingly randomly, several time.  The way it behaved, I suspected I upset an AJAX call.  However, I didn't dig any deeper!

**Comment by jbaird123** [comment]
Resolved. Please reopen if the issue persists.
