### ISSUE TITLE
Make it easier to add properties to a schema after mapping has started

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#390]
Currently, if properties are missed when when uploading the schema & doing the domain mapping, and this is not noticed until after mapping has started, the only remedies are either (a) to go back a stage and re-upload the schema file or (b) to upload just the omitted properties as an separate partial schema.

Option (a) involves the loss of any mapping that has been done, which may have involved considerable effort; option (b) results in fragmented schemas in the output. Neither is viable in the long term, either in terms of usability or when we consider that schema are frequently modified.

A required enhancement going forward is that new properties can be added to existing schemas at any stage.

**Comment by jeannekitchens** [comment]
@jbaird123 please provide a level of effort to correct this one.

**Comment by philbarker** [comment]
relaated #384 & #328

**Comment by jbaird123** [comment]
@jeannekitchens - This will be addressed as part of the fix for #361 which is identified as a bug.

**Comment by jbaird123** [comment]
Resolved with the completion of #361
