### ISSUE TITLE
Make it easier to delete properties from a schema after mapping has started

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#391]
Currently, if too many properties are added when uploading a schema the only way to remedy this is to go back to the schema upload and start again. This will result in the loss of any mapping that has been carried out before the error is noticed, which may be the loss of considerable work. Publishing without mapping is a workable option for now, but it would be better to be able to delete properties from an uploaded schema.

**Comment by jbaird123** [comment]
Resolved with the completion of #361

**Comment by jeannekitchens** [comment]
@philbarker this is a follow up from your note....I added properties postcodeBegin and postcodeEnd to the spine from [schema.org](http://schema.org/). When I delete the property which I mapped as identical, the property in the spine also seems to get removed -- let me know if you see them.

I selected to edit the Organization - Spine
![image](https://user-images.githubusercontent.com/20917206/211655207-ff733495-9a62-481e-9c04-92d5fcf8bb97.png)

**Comment by philbarker** [comment]
Thank you @jeannekitchens I will add this to the documentation when I get the chance (see issue #401 )
