### ISSUE TITLE
Property name wrong during mapping

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#396]
Having imported properties (from schema.org) when mapping them to the spine, their name gets displayed incorrectly
![image](https://user-images.githubusercontent.com/658047/211298501-615c54ab-45e2-4174-a6e0-9a0da668b290.png)

Note that the property in the spine is named "geoURI" and the property being mapped is named "geo", but the name displayed when the property being mapped is dragged into the mapped properties column is "geoURI" when it should be "geo".

**Comment by stuartasutton** [comment]
I have experienced the exact same issue:

<img width="2461" alt="hasRubric-error" src="https://user-images.githubusercontent.com/2939046/214118100-7a7f20ce-bad6-46ae-8d8a-41479e30d87e.png">

**Comment by excelsior** [comment]
There was a bug with displaying mapped terms' names (basically, spine terms' names were displayed instead). The fix has been deployed.

**Comment by jbaird123** [comment]
@philbarker - The fix for this has been deployed; however, I don't see the Geographic URI term in any of the spines, so I can't verify.  Can you let me know if it's working?

@stuartasutton - The example you noted has been fixed.
