### ISSUE TITLE
Drop rdfs:Datatype from the output 

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#40]
@philbarker & @richard0000, currently, the JSON-LD output (as described in the [Output Explainer](https://docs.google.com/document/d/1yR4LYHCD6vRbzE8njQaNw8JkIk0QVHUVRFZeLVPUB-c/edit#)and the [JSON-LD mapping example](https://github.com/t3-innovation-network/desm/blob/master/examples/Mapping_Example.json)) has the following:

`
"desm:datatype": {
        "@id": "xsd:string"
      }`

....and

`
"rdfs:range": {
        "@id": "rdfs:Literal"
      }`

I am questioning the need for desm:datatype.  

In the example, the desm:datatype is xsd:string and the rdfs:range is rdfs:Literal. [R]dfs:range is defined as the property "used to state that the values of a property are instances of one or more classes" (both strings and things). Thus, the range can include datatypes which in RDFS are a subclass of rdfs:Literal.

So, instead of having both as noted above, we simply drop the desm:datatype property and have the following:

`
"rdfs:range": {
        "@id": "xsd:string"
      }
`

Phil, your thoughts.

**Comment by philbarker** [comment]
I had noticed this mentioned earlier. Since you ask for my thoughts: I am not sure about treating xsd:string as an rdfs:Class as it comes from a different type of modelling, and deals with the encoding of a Literal rather than classification of a resource. I note that schema.org declared classes to mirror the common xsd DataTypes and uses these classes for their range and domain statements. That seems more formally correct, but in the context of DESM I suspect it wouldn't make any noticeable difference.

**Comment by richard0000** [comment]
@stuartasutton please let me know the final decision.

**Comment by stuartasutton** [comment]
Phil, I'd prefer to simply reference the [schema.org datatypes](https://schema.org/DataType) rather than declare them in the DESM namespace unnecessarily. However, I'd note that you see the use of the xsd types in this way all over JSON and JSON-LD data as values for rdfs:range (doesn't necessarily make it correct).

**But to the question that stimulated this issue**. I think we should drop the desm:dataType from the DESM schema and let rdfs:range carry the weight. That means that the alignment table in issue https://github.com/t3-innovation-network/desm/issues/37 is correct.

We can use the the schema.org datatypes with the exception of the RDF schema class rdfs:langString (an instance of rdfs:Datatype and a subclass of rdfs:Literal).

**Comment by philbarker** [comment]
@stuartasutton that seems very reasonable (all of it). I don't have a strong preference either way.

**Comment by stuartasutton** [comment]
@richard0000 & @philbarker, here are the changes:

**Edit Term form**

1. Conform the [fields in the form](https://marvelapp.com/prototype/adf7283/screen/68479195) to the (corrected) table at the top of issue #37.
2. Order the fields in the edit form to the same sequence in the table at the top of issue #37.

**Output Explainer (marked updates)** 

1. Deleted `desm:dataType` from the two property descriptions.
2. Added schema.org to JSON-LD context with an `sdo` prefix.
3. Changed `rdfs:range` values in both property descriptions to use [schema.org/DataType](https://schema.org/DataType) for expressing datatyped literals.

**Further rdfs:range information** 
1. Referencing literals:   `"rdfs:range": "sdo:Text"`, `"rdfs:range": "sdo:DateTime"`
2. Referencing language-tagged literals: `"rdfs:range": "rdf:langString"`. (Note: in JSON-LD, such language-tagged literals rely on a language map in the context)
3. Referencing a resource: `"rdfs:range": "credReg:AssessmentProfile"`

**Comment by richard0000** [comment]
@stuartasutton I think the points for **Edit Term Form** are covered in the PR #41 .

Please, take a look at the image attached in that PR and tell me if that's ok.

**Comment by richard0000** [comment]
@stuartasutton this is the order of the elements on the edit term screen right now:

![image](https://user-images.githubusercontent.com/6996951/94604639-58898e00-026e-11eb-8295-d30b31ee3285.png)

Please let me know if that's ok. As mentioned above, the elements are ordered as in the table in the issue #37 and the raw preview is showing the same order as in the [output explainer](https://docs.google.com/document/d/1yR4LYHCD6vRbzE8njQaNw8JkIk0QVHUVRFZeLVPUB-c).

**Comment by richard0000** [comment]
Covered with PR #41

**Comment by stuartasutton** [comment]
@richard0000, the Edit Term Form in PR #41 is looking good; but, the second bullet above at https://github.com/t3-innovation-network/desm/issues/40#issuecomment-700792032 about the order of the fields should be handled before we go on. I ask you to reorder the input fields in the Edit Term Form to match the order in the table at the top of issue https://github.com/t3-innovation-network/desm/issues/37.

**Comment by richard0000** [comment]
@stuartasutton the only difference I can see is the vocabulary which I changed to be on the left of the form in order to avoid making the form too large.

Please let me know if you want that to be changed also.
