### ISSUE TITLE
Spine Broken/Restricted

### ISSUE THREAD

**Issue by 4pins** [t3-innovation-network/desm#402]
Just trying to view shared mappings.  However I can't see multiple spine entries.  Below is an example screenshot.

![image](https://user-images.githubusercontent.com/10967355/211366290-9e3bbfc7-4287-4cfb-920e-8e109b91307c.png)

**Comment by philbarker** [comment]
@stuartasutton saw this too, but I was unable to reproduce it. (I suspect 503 refers to a HTTP The server is currently unavailable error)

**Comment by jeannekitchens** [comment]
@excelsior @jbaird123 any updates happening to the server that could be causing this?

**Comment by excelsior** [comment]
It's a performance issue. There are hundreds of elements in this domain's spine and they loaded individually, one-by-one. I'll make changes to load them at once.

**Comment by stuartasutton** [comment]
Just a note...and not sure it is relevant. This 503 code first appeared after I uploaded three files for ASN--the original and two separate files to pick up properties missed in the original file.

**Comment by jbaird123** [comment]
This has been resolved.
