### ISSUE TITLE
Path Information 

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#404]
The screenshot below shows an example when "Alignment Notes" are included with a mapping.  Visibility of the path would be useful to provide additional context for a mapping.  

@stuartasutton I may not have captured enough about this issue.  Please feel free to add more information. 

![image](https://user-images.githubusercontent.com/20917206/212144498-1d7e1a83-1e2b-46cf-aaac-e6473dd2e7e3.png)

**Comment by stuartasutton** [comment]
My take on this is slightly different, Jeanne. I don't think  "Alignment Note" is the right place for this. I think it should be visible on the bottom of any property where a path has been optionally entered.; i.e., it should be visible without having to click anything.  DESM should work out a common grammar (e.g., like Nate's) for expressing path.

This is obviously a new feature.

**Comment by 4pins** [comment]
So what is this path?  I've been trying to abridge XPaths to uniquely identify fields/elements & attributes/properties.  Is this a path primarily between entities/classes?

**Comment by jeannekitchens** [comment]
@4pins for the above example, the path is from the Competency Class to the Competency Framework Class via a property called isPartOf and the Competency Framework Class contains the repositoryDate property.   With CTDL, the path can often be bi-directional.  

![image](https://user-images.githubusercontent.com/20917206/221306761-21a64474-2e4d-40f3-bfcf-13eee9b17616.png)

**Comment by philbarker** [comment]
@4pins "So what is the path" it'll take some research and experimentation to answer that, but I suspect the useful way of representing a path will depend on the metamodel and encoding syntax used. My starting points would be SPARQL property paths  for RDF, JSONPath for JSON and XPath for XML. It may be that a simple format like Jeanne shows (I guess that is from Nate) could be translated, but not all path specifications will be so simple. Sometimes you need something like "find the Identifier Object with schemeName="xyz" and use the value provided for the "identifier" property of that object.

**Comment by 4pins** [comment]
@philbarker Having gone through the process, that makes perfect sense to me.  However, I'd suggest we note this clearly so users can understand why two mapped fields may appear radically different when comparing paths.

**Comment by jeannekitchens** [comment]
@philbarker this is important so yes to moving it to a priority assuming you'll add a checklist.

**Comment by 4pins** [comment]
My take:

"Can we get the definition of the path"

Path:  A syntactic method for accessing and querying elements within hierarchical data structures, such as XML and JSON, using a sequence of delimited path expressions to navigate and filter nodes or properties.

"with examples"

/Student/FirstName
Student.FirstName

/Student/PrimaryContact/FirstName
Student.PrimaryContact.FirstName

Note:  I'm not sure if we want the full path (exemplified above) or the contextual path (everything but the actual node being addressed).  However, I am sure I want this specified.

"In which format"

As a string in the format entered by the user doing the mapping.

"where do we output it? Is it under Alignment Notes?"

I'd put it just above Alignment Notes as I consider it more fundamental.  To me it should be a separate (optional string) field so it can be leveraged by other systems.

I hope this helps.  But be sure to listen to Phil!

**Comment by jeannekitchens** [comment]
@edgarf @philbarker @jgoodell2 

This issue is directly rated to issue #448 (also tagged as Data Transformation). 

It has been discussed during mutliple project team meetings and [documented with project team notes ](https://docs.google.com/document/d/16_-t7I-St8OjdJQeHfhfCP5SzgOXwjSH-h9dwkR1PIs/edit )and via [DESM Transformations to Support](https://docs.google.com/document/d/16aNbnAVg4SnJJegjTiZttQAHrqR8TAsUxc-CJOZgrOc/edit#bookmark=id.lgrxjzl6ocms).  

During our most recent meeting on June 13, 2024.  The following was documented:

SOLUTIONS AND NEXT STEPS

- Instructions for scoping guidance are necessary and implementing a mapping is to provide the data needed for a third-party transformation tool.
- Mappers need to know they have to upload all properties within a given path.
- The mappers need to know if there always needs to be a reverse path/transform.
- The tool needs to allow two fields for paths as shown with Jim’s mockup [DESM Transformations to Support](https://docs.google.com/document/d/16aNbnAVg4SnJJegjTiZttQAHrqR8TAsUxc-CJOZgrOc/edit#bookmark=id.lgrxjzl6ocms).
- The 1st box is the (left) transform to the spine ← 
- The 2nd box is transfer from the spine →
- Provide users the syntax to utilize.  Either of these can be used.   Ideally the tool should validate the syntax so as not to end up with GIGO.  If validation cannot be achieved initially, the tool needs to show the two examples. 

$spine.person.firstname=$mapped.person.fname
or with some bracketed thrown in
$spine.['Person']['First Name']=$mapped.['Identity']['Name']['Given Name']


![Image](https://github.com/t3-innovation-network/desm/assets/20917206/9f5a90f1-50d3-4a93-802e-a6f7263fd2eb)

![Image](https://github.com/t3-innovation-network/desm/assets/20917206/edb355db-5c7d-413c-a25c-764786f98a12)

**Comment by philbarker** [comment]
We are still not sure "what is the path". When we investigate this we always come around to just adding the property, either directly on the abstract class or by having a new abstract class for it.  This could be addressed by documentation.

There are cases where some sort of JsonPath info might be needed, if for example the mapping of a property depends on the value of another property.

**Comment by 4pins** [comment]
@philbarker In my world it is still XPath see:  http://specification.sifassociation.org/Implementation/NA/4.3/ImplementationSpecification.xlsx

**Comment by philbarker** [comment]
@4pins XPath answers "how to express the path" and we're kind of settled on JsonPath for that but there are difficulties there too (e.g. how to address attributes rather than elements). But we're stuck on "**what** is the path". We find in practice that just adding the property to be mapped works.

**Comment by philbarker** [comment]
@shlag3n @edgarf help me with the QA please: where should I look to see some paths?

**Comment by edgarf** [comment]
<img width="2225" alt="image" src="https://github.com/user-attachments/assets/9b2a0e64-9a2c-44ff-a035-c8c967443ea4">
@philbarker - on the mapping page, there is a new button to add transformation

**Comment by philbarker** [comment]
@edgarf  this is the "path information" issue asking that paths to properties be made visible; that looks like a solution to #448

**Comment by edgarf** [comment]
Sorry, you are right, we got confused, cause a similar topic was mentioned in multiple issues. Oksana implemented the functionality that we discussed to implement as "MVP" for this functionality

**Comment by philbarker** [comment]
No problem, the two issues have often been discussed together because they both ended up involving json path.

**Comment by philbarker** [comment]
OK, I'll move this back to ready and will move issue 448 to QA

**Comment by edgarf** [comment]
The next task for this issue is to connect together and discuss the specific requirements, as those are not completely clear now.

**Comment by philbarker** [comment]
I think we have done all we can for this issue, namely we show the "Domains"/relevant classes of the properties:

When mapping it looks like this:
![image](https://github.com/user-attachments/assets/343f49a5-5f42-4c22-bae6-4094a8b951cf)

In the results it looks like this:
![image](https://github.com/user-attachments/assets/ade29f16-58a4-4c2f-8260-a95c00702339)

(The UI terminology could be more consistent, but that is another issue.)

I don't think we can do more because while it is easy for a human to say the "path to get from what we are mapping to this property is `a>b>c>d`" it is not possible for DESM to know how to do that. 

For example, say the schema used for the spine has an `authorName` property for CompetencyFrameworks but another schema has an `author` property which links to objects of class `Person` with a `name` property. DESM knows that terms in the schema  being mapped come from `CompetencyFramework` and `Person`, but it does not treat these as different. While we know `CompetencyFramework` is the "main" class, DESM doesn't. Even if it did, we couldn't rely on it being able to infer that the right path from `CompetencyFramework` to `name` when `name` is selected is `CompetencyFramework > author > Person > name` because there might be other paths, e.g. `CompetencyFramework > name` or `CompetencyFramework > publisher >Organization > name`. 

And this is assuming that there is anything in the schema about domains and ranges, which is not always the case.

So best we can do is show that name is a property of `Competency`, `Person` and `Publisher` and use the Transformation function to show how to morph the models, e.g. `authorName = $author.name` (in JSONPath syntax).

@jeannekitchens @jgoodell2 @dlawsonQIP @AH1CEDS : I am going to close this issue with this comment. If anyone thinks we should reopen it you can.

**Comment by 4pins** [comment]
So, have I lost the plot?  I don't see how we wind up with crosswalks between data standards without this.  Are we going to limit DESM to RDF data models?  Then I believe I understand how this works.  Even not being the RDF expert on this particular thread.

**Comment by philbarker** [comment]
@4pins  a transformation (recorded separately to what this issue is asking for) gives you what you need to translate data when the property in question is not directly part of the class being mapped.

**Comment by 4pins** [comment]
@philbarker Okay, I think it get it.
