### ISSUE TITLE
Delete "spine" message from Alignment Notes

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#405]
When a property  is added to the spine, an Annotation Note such as follows is added to the property in the viewer:

<img width="1138" alt="AddToSpine" src="https://user-images.githubusercontent.com/2939046/212352334-ea8504d6-c7ed-4011-a966-a1b9fbc7e266.png">

My take is that the Alignment Notes should be reserved for annotations added by the person doing the mapping. As an end user clicking to read a note, these 'added to spine' messages tell me nothing of immediate use. In fact, I became annoyed enough with this repetitive usage of Alignment Note that I stopped looking at them; this is bad because I might well be missing information that would be of immediate utility to me as viewer. 

If I am missing something (quite likely) in the viewing context about the 'added to spine', then display it somewhere else than in Alignment Note.

**Comment by philbarker** [comment]
Suggested Resolution: 
- do not add message / alignment note when adding property to spine.

**Comment by philbarker** [comment]
No comments being added. moving to QA passed. Thank you @excelsior
