### ISSUE TITLE
Problems in JSON-LD download

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#406]
I downloaded the schema.org Person mapping from https://tool.desmsolutions.org/mappings and found objects with null for the @id all over the place, e.g.
```
            "desm:mappingPredicate": {
                "@id": null
            },
```
That's causing me problems with other RDF tools that like their triples to have three things in them.

Can you check (1) why are there so many things with null values, (2) whether it is possible to omit the property when it has no value?

**Comment by excelsior** [comment]
@philbarker The fix is deployed to both production and staging.

**Comment by philbarker** [comment]
Now what I see (in this case in a download of `Phil Barker - Schema.org - Organization (Schema Organization)`)   is
```
            {
                "@id": "http://desmsolutions.org/TermMapping/235",
                "@type": "desm:TermMapping",
                "dcterms:isPartOf": {
                    "@id": "http://desmsolutions.org/TermMapping/9"
                },
                "desm:mappedterm": [],
                "desm:mappingPredicate": {
                    "@id": "https://tool.desmsolutions.org/resources/predicates/Identical"
                },
                "desm:spineTerm": {
                    "@id": "https://tool.desmsolutions.org/resources/terms/founder"
                }
            },
```
Note: no mapped term.

The structure is also odd: the graph is broken down in to arrays of four `desm:TermMapping` for no apparent reason.

I also wonder why some of the  URI prefixes are desm, i.e. in 
```
        "ceds": "http://desmsolutions.org/ns/ceds/",
        "credReg": "http://desmsolutions.org/ns/credReg/",
        "dct": "http://purl.org/dc/terms/",
        "dcterms": "http://purl.org/dc/terms/",
        "desm": "http://desmsolutions.org/ns/",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "sdo": "http://schema.org/",
        "xsd": "http://www.w3.org/2001/XMLSchema#"
```
Why are ceds and credReg namespaces under http://desmsolutions.org?

I'll rename this issue to reflect general problems with mapping download and close #413

**Comment by excelsior** [comment]
The CEDS namespace comes from this document, I believe:

https://docs.google.com/document/d/1tmiCsCvie350l55JTE4w4K3sYdIAk84xXBQnyGyG_QA/edit#heading=h.34u7quuurqe8

Not sure about the CredReg one, though. Please let me know what the correct value is.

Could you kindly share an example of a desired structure for a mapping download? In the meantime, I removed alignments with no mapped terms from export.

**Comment by philbarker** [comment]
I guess we should be asking mappers / SDOs what to use for their namespace identifiers.

Will get back to you with example data, but the schema is here [desmSchema.ttl](https://github.com/t3-innovation-network/desm/blob/main/schemas/desmSchema.ttl) and looks like this 
![Domain_Model-REV-Domain Model-Rev drawio](https://user-images.githubusercontent.com/658047/216972836-998766fe-3297-4acf-85b1-e71fad61d4b1.png)

**Comment by philbarker** [comment]
Note: currently the mapping exports with 
```
{
            "@id": "http://desmsolutions.org/TermMapping/16",
            "@type": "desm:AbstractClassMapping",
            "dcterms:created": "2022-11-23",
            "dcterms:dateModified": "2023-01-19",
            "dcterms:title": "Jim Goodell - CEDS - Organization",
            "dcterms:description": "",
            "desm:abstractClassMapped": {
                "@id": "https://tool.desmsolutions.org/resources/abstract-classes/Organization"
            },
            "dcterms:hasPart": [
                {
                    "@id": "https://tool.desmsolutions.org/resources/terms/address"
                },
```
But `https://tool.desmsolutions.org/resources/terms/address` is not a term mapping, it is a spineTerm

**Comment by philbarker** [comment]
I tidied up the schema diagram:
![Domain_Model-REV-Domain Model-Rev-Domain Model-Rev](https://user-images.githubusercontent.com/658047/217812298-026fe748-7dfd-4fe1-8730-a29a68b2c322.png)

**Comment by philbarker** [comment]
@excelsior there is a gist here: https://gist.github.com/philbarker/759ccd36d0854995db247ab10092fe5d

It is only partial, it only covers the top four of left hand entities in the diagram above, but I hope it is enough for us both to go on for now. Those are the core of the mapping, the rest is context.

Apologies in advance for any errors, I've checked what I can but cannot be sure it is perfect.

It starts with the MappingConfiguration entity. When exporting a Config file this will be mandatory, as would all the other information that exists (bearing in mind that a Mapping Config might not have any mappings in it). For an AbstractClassMapping, you could skip over the MappingConfiguration entity, but I see no harm in including it.

Note that when you get to the end, the `rdf:Property` typed objects, if the original schema is RDF then use `rdfs:subpropertyOf` to point to the original URI, if the original schema is JSON-Schema or XSD, use whatever you can to identify the namespace and an XPath/JsonPath to identify the element. Properties in the spine don't have either.

I've added a fuller context block, I'm not sure if a full context file exists. Tell me if you know of one.

We're going to have to think more in the future about URIs. In the URIs I have used such as `https://tool.desmsolutions.org/example01/terms/03` where `/example01/` represents the mapping project. Putting everything into `/resources/` for all projects risks some nasty collisions between different mapping projects on the same instance.

I see some of the URIs resolve, e.g. https://tool.desmsolutions.org/resources/abstract-classes/Organization but not to full JSON-LD, and there are issues with what is there (in that case there is a "triple" with a null object, and I don't know where the idea of giving an abstract class a sourceURI came from. It's safest to include all the data in the download, I expect DESM instances will come an go, and we want the actual mapping files to be more persistent (this is one reason for including the Mapping Config in the term mapping download).

There's more to do than I (and probably you) can manage during this pilot, but hopefully we can get something usable out and identify required enhancements for the future.

**Comment by excelsior** [comment]
Thanks for the gist, @philbarker, I made the proposed changes. Only alignments with the `No Match` predicate have `null` as their mapped term now.

I use mappings' names and internal IDs in the URIs of exported entities to ensure their uniqueness. None of those can be resolved, though. Which ones of those should be resolved and what exactly should be returned?

Also, does the `desm:hasDSO` property in the config node have a correct value?

**Comment by philbarker** [comment]
Thanks @excelsior we are getting there, I can now load that file into some of the tools I use for RDF. But there are a couple of problems:

1. I should have put  `"@type": "http://www.w3.org/2001/XMLSchema#date"` in the context for  `dct:created` and `dct:dateModified` (not dateTime as the time of creation/modification isn't in the data)
2. Good idea to use the mapping name in the URI for the things that are unique to each mapping, but the URI for the things that are shared between mappings need to be the same, otherwise they're not shared. So only what is uploaded or created by each mapper should have URIs unique to that mapping (that would be properties etc from their schema and the `ClassMapping` and `TermMapping`s they create) everything else should have a URI that is shared between different mappers (especially abstract classes, mapping predicates and spine terms). The abstract classes and mapping predicates were uploaded with identifiers, so best keep them (see [pilotAbstractClasses](https://github.com/t3-innovation-network/desm/blob/main/concepts/pilotAbstractClasses.ttl) and [pilotMappingPredicates](https://github.com/t3-innovation-network/desm/blob/main/concepts/pilotMappingPredicates.ttl)).

**Comment by philbarker** [comment]
@excelsior here is some more detailed information on the changes to URI patterns that need to be made.

1. anything uploaded as a concept scheme during the configuration should keep the URI it had when uploaded, these might be shared across many mapping projects. In the present case we have :
 1.1  abstract classes like <http://desm.org/concepts/person> from [pilotAbstractClasses](https://github.com/t3-innovation-network/desm/blob/main/concepts/pilotAbstractClasses.ttl)
 1.2 mapping predicates like <http://desmsolutions.org/concepts/identical> from [pilotMappingPredicates](https://github.com/t3-innovation-network/desm/blob/main/concepts/pilotMappingPredicates.ttl)
 [aside: there were lousy choices on my part, but they are what we used, in future cases hopefully people will make better choices. The general rule is use what was provided in the config]
2. Everything that is shared across the whole mapping project needs to have a URI shared across all mappings in the project. Let's call this mapping project pilot01, so: 
  2.1 instances of MappingConfig, DSO, Agent, Schema should all have URI stems like `https://tool.desmsolutions.org/pilot01/<whatever>`, e.g. https://tool.desmsolutions.org/pilot01/mappingConfig
  2.2 the spine is shared, let's call it `https://tool.desmsolutions.org/pilot01/<class>/spine` and the terms in it `https://tool.desmsolutions.org/pilot01/person/spine/<nnn>` e.g. `https://tool.desmsolutions.org/pilot01/person/spine/123`
3. The things created by an individual mapper (ClassMapping, TermMappings) can keep the URI pattern you have now, though it's probably overkill, I think `https://tool.desmsolutions.org/pilot01/<Class>/termMapping<nnn>` would do and would fit the pattern of the other URIs (I am assuming that the number you currently use after termMapping is unique across all users).

Also:
1. Those fixes to the context for dates mentioned in the previous post
2. Another error of mine from the gist: the id of the DSO used with `desm:hasDSO` needs not to be the id of the mapping, it should be `https://tool.desmsolutions.org/pilot01/<whateverDSO>` e.g. `https://tool.desmsolutions.org/pilot01/CEDS`
3. the value for desm:hasClassMapping should match the @id of the ClassMapping, i.e. `http://**tool.**desmsolutions.org/...`
4. The rdf:Property data is missing from the download (last block in the gist), it's needed for every spineTerm and mappedTerm.
5. The values for "dct:description" in the data I downloaded are just the placeholder text from the gist
6. For the full config you will need the data about the things I didn't put in the gist (rdfs:Class, DSO, Agent, Schema and ConceptScheme and Concepts)

**Comment by excelsior** [comment]
@philbarker Thanks for the feedback. I made most the changes requested. The latest version is available on prod.

The configuration profile's slug with its internal ID is used as the URI stem instead of the mapping's slug and ID now.

I'm not sure how to call the properties of the missing things in the config (i.e. Agent and Schema, etc.).

Also not sure how should `"desm:inSchema"` look like (currently, I simply use the value from the gist).

**Comment by philbarker** [comment]
Thanks, will check that later this week.

> I'm not sure how to call the properties of the missing things in the config (i.e. Agent and Schema, etc.).
See [diagram](https://github.com/t3-innovation-network/desm/issues/406#issuecomment-1424116602).  

> Also not sure how should "desm:inSchema" look like (currently, I simply use the value from the gist).
Do you have an object that describes the schema uploaded by the mapper? (bottom right in the schema diagram) It should be the URI for that object.

**Comment by philbarker** [comment]
@excelsior this is still broken, as you suspected the value for desm:inSchema is wrong.   (see below for what goes wrong with this export)

- [ ] What we need is for the value of desm:inSchema to be the URI of the schema that the property is in.

The [gist](https://gist.github.com/philbarker/759ccd36d0854995db247ab10092fe5d) does in fact show this -- the four Property objects at the end each have a different value for desm:inSchema showing which schemas they come from, though of course the example/placeholder URIs in the gist might not be the same as you use.

A couple of other points:

- [ ] Please make the value for rdfs:domain a URI
- [ ] Note that the properties in the spine do not have a rdfs:subProperty property.



Explanation of what goes wrong:

When I export the CEDS, CTDL and Schema.org mappings for Organization from DESM and load them into a triple store, and query for properties in the spine : 

```
PREFIX desm: <http://desmsolutions.org/ns/> 
PREFIX spine: <https://tool.desmsolutions.org/DESM+Pilot%3A+Competency%2C+Organization%2C+and+Person-1/Schema/syntheticSpine> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?label ?comment WHERE {
    ?prop desm:inSchema spine: ;
          rdfs:label ?label ;
          rdfs:comment ?comment .
}
```
I find 259 properties where the DESM tool says there are 106 properties in that spine.

When I look at the output from DESM I find things like:

```
        {
            "@id": "https://tool.desmsolutions.org/DESM+Pilot%3A+Competency%2C+Organization%2C+and+Person-1/Organization/spine/392",
            "@type": "rdf:Property",
            "rdfs:label": "email",
            "rdfs:comment": "Email address.",
            "rdfs:domain": "Organization",
            "rdfs:subPropertyOf": "sdo:email",
            "desm:inSchema": "https://tool.desmsolutions.org/DESM+Pilot%3A+Competency%2C+Organization%2C+and+Person-1/Schema/syntheticSpine"
        },
```
in CEDS

and 
```
        {
            "@id": "https://tool.desmsolutions.org/DESM+Pilot%3A+Competency%2C+Organization%2C+and+Person-1/Organization/spine/392",
            "@type": "rdf:Property",
            "rdfs:label": "email",
            "rdfs:comment": "Email address.",
            "rdfs:domain": "Organization",
            "rdfs:subPropertyOf": "sdo:email",
            "desm:inSchema": "https://tool.desmsolutions.org/DESM+Pilot%3A+Competency%2C+Organization%2C+and+Person-1/Schema/syntheticSpine"
        },
... 
       {
            "@id": "https://tool.desmsolutions.org/DESM+Pilot%3A+Competency%2C+Organization%2C+and+Person-1/terms/6134",
            "@type": "rdf:Property",
            "rdfs:label": {
                "en-US": "Email"
            },
            "rdfs:comment": {
                "en-US": "Email address of the organization or person."
            },
            "rdfs:domain": "Organization",
            "rdfs:subPropertyOf": "ceterms:email",
            "desm:inSchema": "https://tool.desmsolutions.org/DESM+Pilot%3A+Competency%2C+Organization%2C+and+Person-1/Schema/syntheticSpine"
        },
```
 So what the data says is that every property is a member of the spine, and it doesn't tell me what schema they actually came from.

**Comment by excelsior** [comment]
@philbarker I fixed all of the issues, please take a look.

> Do you have an object that describes the schema uploaded by the mapper? (bottom right in the schema diagram) It should be the URI for that object.

We do, and I added schemas to the export. However, we don't track abstract class and mapping predicate uploads separately, so there are no such objects for them. Hence the exported concept schemes lack the `desm:relatedSchema` property.

**Comment by philbarker** [comment]
Woot woot woot, it works! 

See https://docs.google.com/document/d/1z11oZvgAsUBsJgVnf4-cPlG5ZzwxVZqdRB1u_qzd_N0/edit for a little of what can be done with it.

(Okay there are a couple of niggles that need thinking through about namespace URIs and getting the `@context` block right, but they can be carried into the next phase.)

@excelsior thank you for your patience as we worked this out.
