### ISSUE TITLE
Viewing previously mapped property shows incorrect information

### ISSUE THREAD

**Issue by slackhalyard** [t3-innovation-network/desm#415]
<img width="1076" alt="Screen Shot 2023-01-30 at 7 51 59 PM" src="https://user-images.githubusercontent.com/68451260/215640582-d106941b-be79-4009-880a-34fa8784dcd6.png">
This image shows "Middle Name" mapping. It looks as though it's been mapped to "Non Immigrant Visa Status Change Code". If you look at the name of the mapped term, you can see it's really "Middle Name".  Importantly, "Middle Name" was added directly to the spine. "Non immigrant Visa Status Change Code" was not mapped to "Middle Name".

**Comment by jeannekitchens** [comment]
@slackhalyard thank you.  This issue is being addressed.

**Comment by jbaird123** [comment]
@slackhalyard - This has been resolved.
