### ISSUE TITLE
Add definition of mapping predicate to "View Mappings" screens

### ISSUE THREAD

**Issue by jbaird123** [t3-innovation-network/desm#418]

**Comment by philbarker** [comment]
- [ ] add mapping predicate in such a way that it is always visible but less prominent than predicate label.

**Comment by edgarf** [comment]
@philbarker Could you please reference a page that is in mind?

**Comment by philbarker** [comment]
@edgarf This refers to mapping predicates, and affects any screen where a mapping is shown, e.g. when selecting View Mappings and View Shared Mappings (I will update the title to better reflect this).

So, for example on https://gopher.desm.staging.c66.me/mappings-list?abstractClass=Location & profile PhilTest1 the mapping predicate is "Identical" in a green box.
![image](https://github.com/t3-innovation-network/desm/assets/658047/ff45300a-162f-4926-82e5-6f9e1102f76b)

**Comment by philbarker** [comment]
Yes, the definitions are shown on the mapping screen while mapping is in progress

![Image](https://github.com/t3-innovation-network/desm/assets/658047/c168bff7-6ca5-4de9-8ade-2baeac352520)

and on the view mapping screen

![Image](https://github.com/t3-innovation-network/desm/assets/658047/66067da6-5727-4c73-9f4a-4d5de3b26c48)


All good, mving to QAPasses.
