### ISSUE TITLE
Parsing of the schema into the Edit Form

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#42]
@jbaird123, @richard0000 (@jeannekitchens), now that the fields in the "Edit Term" form align to the Output Explainer and, as a result, to terms in RDF Schema, I have two questions about the parsing of the data from the schema being mapped **into** the form. 

Q1: In our next demo, we will be able to see the Edit Form fields of the form automatically populated directly from the RDF (json-ld) source file. Is this correct?

Q2: I understand that handling PESC (XML) and HR Open (JSON) are yet to be done and the focus now is on using the schemas already in RDF (e.g., schema.org, Credential Engine, ASN) to flesh out the basics up through the actual mapping. However, when we do get to JSON and XML, the work just completed on the Edit Form **will be identical** and that what we will see in the Raw pane of the form will be the RDF (JSON-LD) translation of the XML and JSON input files based on JSON Schema and XML Schema.  Is this correct?

**Comment by richard0000** [comment]
@stuartasutton 

**For Q1:** I think we need **more clarification** on the question but maybe you can let me know which parts need to change and how on the next image (which is the current status of the edit form):

![image](https://user-images.githubusercontent.com/6996951/94929838-fe6e1000-049b-11eb-9bdd-cfd75d9df4cd.png)

**For Q2:** Correct.

@jbaird123 FYI.

**Comment by stuartasutton** [comment]
@richard0000, my first question asks whether the next demo can demonstrate the **automatic** population of the fields on load. For example, in the form, the "Source URI" field would not still have a text prompt but would have been auto-populated with [[credreg:codedNotation]]. The "Property URI" field would have been auto-populated with [[desm:codedNotation]]. The "Property Label" field would have been auto-populated with "Coded Notation".  The same would be the case with the "Range" and, if there had been one, for "Vocabulary".  

So the question is: Are the fields auto-populated based on the RDFS in the JSON-LD input file?  I have been assuming that they are correct given the auto-population of the range; but am uncertain because of other the fields not being auto-populated when the could have been.  So, I just want a verification that what I am saying here is correct.

**Comment by richard0000** [comment]
@stuartasutton The fields **are auto-populated indeed**. The ones that are not:

- **Source URI:** I'm not sure what to write in it since, for the case of codedNotation, by example, "credreg:codedNotation" doesn't exist in the node with id: "ceterms:codedNotation" and id: "rdfs:Class":

```
    {
      "@type": "rdf:Property",
      "@id": "ceterms:codedNotation",
      "rdfs:label": {
        "en-US": "Coded Notation"
      },
      "rdfs:comment": {
        "en-US": "Set of alpha-numeric symbols that uniquely identifies an item and supports its discovery and use."
      },
      "dct:description": {
        "en-US": "Examples include the alpha-numeric code \"CCSS.MATH.CONTENT.HSA.CED.A.2\" identifying a node in the U.S. Common Core State Standards on creating equations in algebra, or, the code \"8021\" in the U.S. Standard Industrial Classification (SIC) for identifying the occupational context for \"Offices and Clinics of Dentists\"."
      },
      "vs:term_status": "vs:stable",
      "meta:changeHistory": "http://credreg.net/ctdl/termhistory/ceterms/codedNotation/json",
      "schema:domainIncludes": [
        "ceterms:ApprenticeshipCertificate",
        "ceterms:AssessmentComponent",
        "ceterms:AssessmentProfile",
        "ceterms:AssociateDegree",
        "ceterms:BachelorDegree",
        "ceterms:Badge",
        "ceterms:BasicComponent",
        "ceterms:Certificate",
        "ceterms:CertificateOfCompletion",
        "ceterms:Certification",
        "ceterms:CocurricularComponent",
        "ceterms:CompetencyComponent",
        "ceterms:CourseComponent",
        "ceterms:Credential",
        "ceterms:CredentialAlignmentObject",
        "ceterms:CredentialComponent",
        "ceterms:Degree",
        "ceterms:DigitalBadge",
        "ceterms:Diploma",
        "ceterms:DoctoralDegree",
        "ceterms:ExtracurricularComponent",
        "ceterms:FinancialAlignmentObject",
        "ceterms:GeneralEducationDevelopment",
        "ceterms:JobComponent",
        "ceterms:JourneymanCertificate",
        "ceterms:LearningOpportunityProfile",
        "ceterms:License",
        "ceterms:MasterCertificate",
        "ceterms:MasterDegree",
        "ceterms:MicroCredential",
        "ceterms:OpenBadge",
        "ceterms:ProfessionalDoctorate",
        "ceterms:QualityAssuranceCredential",
        "ceterms:ResearchDoctorate",
        "ceterms:SecondarySchoolDiploma",
        "ceterms:SelectionComponent",
        "ceterms:TransferValueProfile",
        "ceterms:WorkExperienceComponent"
      ],
      "schema:rangeIncludes": [
        "xsd:string"
      ]
    }
```

**vocabulary:** In the first state, I assumed we don't have vocabulary related, so we show the user that he/she can upload one and link it to the term.

If you give me instructions on how to get or generate those inputs, I can add it to the automatic population like the other attributes.

**Comment by stuartasutton** [comment]
Ah, I see the problem. Credential Engine (the source) does **not** use the prefix `credreg`. It uses `ceterms`. So the "Source URI" for this property is `ceterms:codedNotation`--or in full,  `https://purl.org/ctdl/terms/codedNotation`. In the value for "Source URI", always use the prefix provided in the data or the full URI.

I am not sure what you mean by:
> and id: "rdfs:Class"

The `rdfs:Classes` of concern to a property in RDF is with its domain and range. You have captured the both already.

**Comment by richard0000** [comment]
Ok, @stuartasutton so then the answer for Q1 is also: correct. 😄

**Comment by stuartasutton** [comment]
Sorry, didn't complete my comments. You are correct, there is no "Vocabulary" with the `ceterms:codedNotation`. I want to go over when the range of a property is a vocabulary at our bi-weekly meeting on Monday (October 5).

**Comment by stuartasutton** [comment]
@richard0000, in the image above, it is not correct.  You have `ceterms:codedNotation` as the "Property URI" when it is the "Source URI". The "Property URI" would be the URI in the DESM namespace--i.e., `desm:codedNotation'.

**Comment by richard0000** [comment]
@stuartasutton ok. How the Porperty URI would be generated? Do you think a formula like the next one would work?:

`("desm:" + <term-uri-in-the-uploaded-spec>)`

**Comment by stuartasutton** [comment]
Close, with one caution. In the imaginary URI--https://desmsolutions.org/terms/d2l/asn/name--arriving at desm:name means more than just the namespace (https://desmsolutions.org) but includes any path right up to the token "name".

**Comment by stuartasutton** [comment]
By the way, you's also see use of the hash like this: https://desmsolutions.org/terms/d2l/asn#name.  The result is the same.
