### ISSUE TITLE
Provide information on why mapping cannot be saved

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#420]
Several mappers have reported that they cannot save their work. On the occasions where we have identified the reason for this it has been because of an incomplete term mapping (i.e. a mapping predicate has been selected for a spine term but there is no mapped property). It is difficult to spot this type of error when there are a lot of terms in the spine, especially if you don't know that is what you are looking for.  In such circumstances there should be a reason displayed for why it is not possible to save. At a minimum a message such as "some term mappings are incomplete", ideally display or highlight which are incomplete.

**Comment by philbarker** [comment]
Here is what you see when the mapping can be saved:
![image](https://github.com/t3-innovation-network/desm/assets/658047/d9e6689c-47cd-41d9-809c-b168c96a9e25)

Here is what you see when the mapping cannot be saved:
![image](https://github.com/t3-innovation-network/desm/assets/658047/89d10ffa-b84e-4f5d-acc5-dae08aee61e2)

**Comment by philbarker** [comment]
I encountered some issues with an old mapping. 

It  cannot be saved and there is no information on why. There may be some underlying problem other than the one being addressed here as I could not recreate with a different mapping.
You can see the issue on this screen cast: https://www.pjjk.net/temp/DESMVids/simplescreenrecorder-2024-03-01_10.10.42.mkv
Two other screen casts show my attempts to reproduce the issue: https://www.pjjk.net/temp/DESMVids/simplescreenrecorder-2024-03-01_10.20.16.mkv & https://www.pjjk.net/temp/DESMVids/simplescreenrecorder-2024-03-01_10.28.43.mkv

If you can figure out what is wrong there, great; otherwise let's assume there is some underlying issue with that mapping an move on.

Two other issues (related to each other) illustrated in those videos:

- The warning message about saving sometimes closes automatically, sometime requires a click to close it
- when it closes automatically it does so too quickly.

To resolve both of these:
- [ ] The warning dialog box about why a mapping cannot be saved should always require a click to close it.

**Comment by shlag3n** [comment]
@philbarker updates re waning dialog were deployed on staging.

As about mapping it can't be saved because some properties that were part of that mapping were removed, but corresponding mappings (alignments) were not and data became inconsistent. We need to decide what to do in this case - remove corresponding mappings (single row), show warning and don't allow to remove property if any active alignments, etc. 
And it'd be great to add this to separate issue along with other things we've found like issues with removing mapped properties/partial mapping saving at the dialog (cc @edgarf).

**Comment by shlag3n** [comment]
@philbarker, @edgarf  fyi - it's easy to fix current inconsistency in mapping data on staging (remove alignments for properties that were removed), lmk if you want me to do that.

**Comment by philbarker** [comment]
> @philbarker, @edgarf fyi - it's easy to fix current inconsistency in mapping data on staging (remove alignments for properties that were removed), lmk if you want me to do that.

Yes, @shlag3n  please do that... or thank you for doing that, if I'm interpreting your last message correctly.

**Comment by shlag3n** [comment]
@philbarker yep, it's already fixed on staging.

**Comment by philbarker** [comment]
@shlag3n I'll the separate issue about removing mapped spine terms.

This issue has now passed QA :-)
