### ISSUE TITLE
Provide more info / context for mapped properties

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#421]
The properties mapped to the spine should have more information about how they "connect" to the domain being mapped. For example instead of postalCode could be Person.address → PostalAddress.postalCode.

Important to emphasize this even when property is directly connected to show that, for example name is Person.name not, say, the name of the person's employer (which could be Person.employer → Organization.name)

(Note, this could be difficult to do automatically for RDF based stds)

**Comment by philbarker** [comment]
Important for accurate mapping. Related to #404 which is high priority.

**Comment by edgarf** [comment]
@philbarker could you provide more details and specifics on this task?

**Comment by philbarker** [comment]
Suggested resolution, when issue #404 is resolved so that we have path information for properties, the information card for mapped properties when **both mapping and displaying results**,  that is on cards for both mapped and unmapped properties on the "align and fine tune" mappings screen


![Image](https://github.com/t3-innovation-network/desm/assets/658047/4f4b5da3-b110-406a-b27b-35cefa8908b8)

**and** on the view of completed mappings

![Image](https://github.com/t3-innovation-network/desm/assets/658047/d9a5f9d3-2023-4c98-b5c1-ab1558575708)

should include (where known / as appropriate):


- [ ] the property's domain / the class that contains the property (remember only the ones relevant to the abstract class being mapped, i.e. those selected during the domain mapping stage) 
- [ ] the path to get to the property
- [ ] the property's range / expected value type / expected value datatype

(I have some ideas about how we might better display this info in mapping result, which I will circulate for comment and add to this issue if folk agree.)




While you are at it, could you tidy up the information displayed on the mapping cards. Currently they look like this:

![Image](https://github.com/t3-innovation-network/desm/assets/658047/dea1c617-4334-49c4-b7f0-cf901b80ad76)

—for a CEDS term that came from a spread sheet in https://gopher.desm.staging.c66.me/mappings/252/align (user phil+ceds@pjjk.co.uk)

or like

![Image](https://github.com/t3-innovation-network/desm/assets/658047/123c5a8c-b153-4060-82f3-8188f7076984)

—for a schema.org term from RDF/S vocab definition in https://gopher.desm.staging.c66.me/mappings/279/align (user phil+sdo@pjjk.co.uk)

Please can we make them all look as close to the second example, i.e. 
- [ ] no opaque URIs in place of name or ID, use what is in the uploaded file for these, and where possible shorten the URIs with namespace prefixes.

Finally on the mapping page, the origin for the properties is showing as the organization that uploaded it. 

![Image](https://github.com/t3-innovation-network/desm/assets/658047/267863de-caa3-4e26-a327-5e893eb7c283)

- [ ] Please change the origin of properties on the spine to be the schema name and version

**Comment by philbarker** [comment]
Here's how we would like to display the info in a mapping result:


![Image](https://github.com/t3-innovation-network/desm/assets/658047/d9f78ff7-ea80-408c-84c0-45fce6a78228)

**Comment by philbarker** [comment]
Copying from slack conversation:
edgar: Can you help orienting us on the attribute Expected Value Type? What should be the possible options there and where do we get it? 
phil: It'll be the class or datatype for values of the property, it'll come from the schema, for RDF/S it'll be the range/rangeincludes property, for JsonSchema it'll be the type property, for xml schema it'll the xsd:dataType of the element if it has a simple value or it'll be a complex type.

**Comment by philbarker** [comment]
Let's drop the path information because in #404 we never specified how to find it. Everything I can think of ends up being Class.property and we are already displaying both Class and property.

**Comment by philbarker** [comment]
@shlag3n Looks pretty good, definitely an improvement, thank you. On seeing the results in context, I a further request: can we separate the property name from the schema name and version. Something like 
     **Schema:** ELM Micro-Credential. **Property:** Expiration date

(I'm looking at https://gopher.desm.staging.c66.me/mappings-list?cp=47&abstractClass=Assertion)

I hope that's not a big ask, sorry for not thinking of it earlier.

**Comment by shlag3n** [comment]
@philbarker thank you, updated and deployed on staging (gopher).

**Comment by philbarker** [comment]
Looks good, thank you!
