### ISSUE TITLE
XSD Support Guidance

### ISSUE THREAD

**Issue by 4pins** [t3-innovation-network/desm#425]
I'm going to leave a few thoughts here in the hopes it helps the T3 Innovation Network make judicious decisions supporting XSD going forward.

Currently the system scans the uploaded files for types and presents them to the user.  The user then selects all the relevant types for the domain they are mapping.  It does not follow the hierarchy of the XSD at all.  Which makes catching fields include through extension or restriction hard if not impossible (I failed at this in a few places).  _However, this is probably the best approach!_  As standards like SIF move to support JSON, we tend to be slowly moving our XSDs away from Russian Doll (Garden of Eden and Salami Slice) patterns towards Venetian Blind.  This means that all elements are declared locally and your software as designed will only work better and better.  Of course it would be great to document what you support.

If you would like more details about how we are striving to define our data standards, let me know.

**Comment by philbarker** [comment]
This is mostly a documentation issue, but the documentation team will need support from Learning Tapestry in understanding what features of XSD are supported.

**Comment by philbarker** [comment]
@edgarf to provide info on what is supported in XSD as part of #350
