### ISSUE TITLE
Editing the definition of a property

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#433]
Looking for the ability to edit the definition (or potentially name) of a property after it has been mapped.

We thought that deleting and re-adding the element may not be a good idea because of implications for what that element is already mapped to.

**Comment by stuartasutton** [comment]
@DMSaunders, can you provide a context when you'd want to edit an element, particularly to change the definition? If a property definition is to be changed, shouldn't that take place at the root--in the schema? But if you change the definition of a property after others have mapped to it, you have already affected their mappings. I think I need more contextual info.

**Comment by DMSaunders** [comment]
It does raise some questions for us which we have not answered yet:
What happens if it's part of the spine?
What does it mean for other properties it's been mapped to?
Who should be notified?
What amount of editing should constitute a nonmaterial change (ie a typo) vs a material change?
Should a material change constitute an upversion? 
Should there be a difference in how a mistake in the definition written in DESM is corrected vs a change has been made to the official definition and someone is updating what's in DESM?

**Comment by philbarker** [comment]
Here is an example of what sometimes gets imported that clearly needs editing:
![image](https://github.com/t3-innovation-network/desm/assets/658047/50dc915d-7767-4ee7-8794-e05506eca419)

**Comment by jeannekitchens** [comment]
@philbarker yes to moving this as a priority.  There has to be a way to clean up properties. With that said, I know I've seen the edit screen. It does/did exist.  When and where is it visible?

**Comment by philbarker** [comment]
@jeannekitchens it is possible to edit the spine, but I haven't seen anything similar for non-spine properties.


**Suggested resolution:**
On the mappings view, https://tool.desmsolutions.org/mappings there is a ![Image](https://github.com/t3-innovation-network/desm/assets/658047/aa9141b1-fdcf-49d9-a0a9-53819d6569b3) icon next to the Spine entry in the list: 


![Image](https://github.com/t3-innovation-network/desm/assets/658047/43a37e61-c88a-4fb0-8334-4972e2b6fafb)

This leads to a view of the spine that has a view of the properties in the spine each with  ![Image](https://github.com/t3-innovation-network/desm/assets/658047/aa9141b1-fdcf-49d9-a0a9-53819d6569b3) icon again. That leads to an editing term screen:

![Image](https://github.com/t3-innovation-network/desm/assets/658047/daab8153-3424-429a-a391-187303bd58e5)

- [ ]  Implement something similar for the properties in the uploaded schema.

BTW do we have a different icon we can use for editing the mapping? It is confusing that the ![Image](https://github.com/t3-innovation-network/desm/assets/658047/aa9141b1-fdcf-49d9-a0a9-53819d6569b3) icon leads to editing property defintions and editing mappings on the same screen.

**Comment by jeannekitchens** [comment]
Editing properties need to be consistent and supported whether in the spine or aligned to it.

**Comment by edgarf** [comment]
Additional findings from Oksana, about breaking functionality (cc @philbarker ) 
- [ ] When doing "edit", then in most places only the comment gets updated, not the other fields.

**Comment by philbarker** [comment]
I have some questions about the UI for editing properties, 



![Image](https://github.com/t3-innovation-network/desm/assets/658047/dc841bd5-cb92-42b1-9796-e8ad645c6869)



like 

- why show the JSON?
- is it possible to edit domain and range?

but am moving this to QA passed because we can do what we ask to be able to do: i.e., edit labels and descriptions in a consistent manner.  We can polish the UI later.

**Comment by shlag3n** [comment]
@philbarker we have a separate issue for the edit term ui (#372), here current functionality was reused without any changes.

**Comment by philbarker** [comment]
@shlag3n I had forgotten about that issue, thanks for the reminder.  And thanks for the work on this: I didn't mean to suggest it was less than we hoped for in any way!

**Comment by AH1CEDS** [comment]
@edgarf , I created a new mapping (Person(Schema.org) – ver 2024.05.20-https; https://tool.desmsolutions.org/mappings) and was able to successfully edit property labels and definitions of the mapped terms. As one edits the label / definition, the changes are reflected in raw JSON under "rdfs:label" and "rdfs:comment," respectively. All looks good.
