### ISSUE TITLE
Ability to re-import / add schema files & properties once mapping has started

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#441]
Often something gets missed when first uploading a specification and doing the domain mapping: properties/domain classes might not be selected for import or there might be an additional file that has some of the required properties.
It should be possible to re-do the whole file-upload and property selection stage of the mapping for a mapping that has already been started without undoing any work that has been done.
If this is currently possible (we know we discussed similar needs before) the UI should be more clear as to how to do it.

**Comment by jeannekitchens** [comment]
@philbarker yes to dropping this into priority 1.

**Comment by philbarker** [comment]
Example work flow required
1. start with a standard that is already part of mapping, even marked as complete. 
![Image](https://github.com/t3-innovation-network/desm/assets/658047/e76e4a81-61e8-4d7d-a0df-ae94b159da08)
2. Click on the ![Image](https://github.com/t3-innovation-network/desm/assets/658047/93c360af-ddc3-449b-bab3-de3a946df05a) button to mark it back to "in progress"
3. Click on the ![Image](https://github.com/t3-innovation-network/desm/assets/658047/93c360af-ddc3-449b-bab3-de3a946df05a) button to mark it back to "uploaded" 
- Currently this is as far back as you can go:
![Image](https://github.com/t3-innovation-network/desm/assets/658047/b1c57ed1-03cb-46b4-bf07-4c24103a0d8b)
 The option to edit goes to the "Domain mapping" screen which allows any already uploaded properties to be mapped to the abstract class. The mappings that were present at step 1 are preserved
5. There should an option to "upload more properties" which would allow properties that were not uploaded to be added.

Or
1. at either the domain mapping stage or the align and fine-tune screen, there should be an option to "upload more properties" which would allow properties that were not uploaded to be added.

- [ ] Add option to upload more properties to the Domain Mapping screen, Align and Fine Tune screen and to My Mappings summary page 
  - Any current domain or property mapping should be maintained
  - Duplicate properties uploaded should be ignored (with info given to user)

**Comment by edgarf** [comment]
After the meeting yesterday, below are the decision points (@philbarker please review if you agree and whether I didn't miss anything).


1. Allow for a user to switch between  "Steps" by clicking the nav items above. Make them clickable, underlined with a hover, and look like a button (let's try by making it an actual link?)

<img width="719" alt="image" src="https://github.com/t3-innovation-network/desm/assets/5213372/1bc39ccc-6f49-45ec-99ca-120b77a6e7d3">

2. Allow to click on the arrow back one more time, when you are in status "Uploaded", to convert status into "Ready to Upload"  
<img width="494" alt="image" src="https://github.com/t3-innovation-network/desm/assets/5213372/b99bf5e1-20b6-4586-a0c8-4dcca5e5008c">


3. When you are on the upload screen, dont remove already imported classes, only add new ones.

**Comment by philbarker** [comment]
@edgarf that's what we agreed :+1: 


Also, 
In point 3, we noticed that it will be important to make sure that the user doesn't change the abstract class they are working on. (Currently they see a choice of abstract classes to upload for, but here we are uploading more properties for a mapping in progress so it would be pretty confusing if they suddenly involved another abstract class!)

4. If a class newly imported in 3 shares a property with other already imported classes that is mapped to the abstract domain class in the domain mapping step, be sure to add that class to the "relevant classes" of that property (see #453 for relevant classes)

**Comment by edgarf** [comment]
Thank you! @shlag3n see some updates above.

**Comment by philbarker** [comment]
This really looks good. I've checked the basic functionality and it's great. I think we'll need to test it out fairly thoroughly, but I'm happy to do that through a training project on the T3 production site.

**Comment by AH1CEDS** [comment]
@edgarf , I was able to re-import schema files and add properties after the mapping has started or has been completed. For reference, my original mapped schema had 49 properties (initially uploaded by selecting C200275 CEDS class/domain for the Person abstract class).

I used a back arrow on the https://tool.desmsolutions.org/mappings screen to change the status of the mapped schema to “in progress” and to “uploaded” and then made and saved the updates from each of the respective starting points. 

As requested by Phil in a prior comment from Feb 20, 2024, duplicate properties have been ignored when I chose the same C200275 class when re-uploading the file. However, no info was provided on the screen to explain that duplicate entries were not / would not be added (I can add this to the documentation).

Also, additional properties have been added only when I selected a single new class (domain) (C200282; with 2 properties) in the upload step (screenshots set 1). Two new properties were then added for a total of 51 properties.

When I selected both the original class (domain) (with 49 previously imported properties) as well as the additional class (with 2 new properties), the result was that all of the updates were ignored. Even though the Preview Your Upload screen showed 51 properties, upon clicking “Looks good,” the next screen showed only the 49 previously imported properties (screenshots set 2).

_**screenshots set 1**_
![image](https://github.com/user-attachments/assets/cfe5b0d8-6379-4b32-8284-3756659dbb89)
![image](https://github.com/user-attachments/assets/c3ffbcd7-a351-4748-a4a3-703d55b809f1)
![image](https://github.com/user-attachments/assets/273fc8d5-b58c-4786-b570-1953ceeefb27)


_**screenshots set 2**_
![image](https://github.com/user-attachments/assets/8e6ebb17-7f43-43e0-b14e-5d7ef04c9d2b)
![image](https://github.com/user-attachments/assets/02c8b8ec-eb9c-4185-80f7-cea07cec5809)
![image](https://github.com/user-attachments/assets/f2938119-a3b4-4d97-846f-c00faad41dce)

**Comment by AH1CEDS** [comment]
[@excelsior](https://github.com/excelsior),

Attached are the 2 files I used (both are ttl files that I saved as txt to be able to attach in GitHub; let me know if you’d like me to convert them to the CSVs). Phil provided both of the ttl files for testing / demo purposes in [this folder](https://drive.google.com/drive/folders/16x8Uz7UmqEPaENCUoK05FhUrz0OhoZil).
[schemaorg-current-https_2024-05-20.ttl.txt](https://github.com/user-attachments/files/16272221/schemaorg-current-https_2024-05-20.ttl.txt)
[CEDS-Ontology-V12.1.0.0-noVocabs.ttl.txt](https://github.com/user-attachments/files/16272222/CEDS-Ontology-V12.1.0.0-noVocabs.ttl.txt)

**Comment by dlawsonQIP** [comment]
Verified re-import and add properties on gopher staging once mapping has started.
