### ISSUE TITLE
Opaque URIs for class/type

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#444]
Sometimes the class/type is given as an opaque URI, as in the screenshot below, which is not very helpful. The screenshot also shows more useful prefixed short URIs / CURIes.
![image](https://github.com/t3-innovation-network/desm/assets/658047/032f5009-032a-4ba7-91cc-7ad433303d88)

(screen shot from Credential Engine Rubric mapping at https://desm.credentialengine.org/ )

I think the long URIs come from non-RDF schemas.

This is a human-facing interface, so human readable labels would be the best thing to display.

/cc @jeannekitchens

**Comment by philbarker** [comment]
Suggested fix:
- [ ] The text in the "class/type" box should match the text in the uploaded schema(*), and not include URI stems added by DESM. (*in the future we might make an exception when we can make compact URIs with a namespace prefix rather than use a full URI; for now use Compact URIs if there is a choice between those and full URIs)

This should be fixed everywhere that the domain/class of a property is displayed (e.g. upload, initial domain mapping, property mapping and display)

**Comment by excelsior** [comment]
@philbarker I implemented the suggested fix. Properties from non-RDF specifications (like CEDS) which get customly converted to JSON-LD only have opaque DESM URIs. The Class/Type of such properties is empty, since we have no value to display.

**Comment by philbarker** [comment]
@excelsior 
>  Properties from non-RDF specifications (like CEDS) which get customly converted to JSON-LD only have opaque DESM URIs. The Class/Type of such properties is empty, since we have no value to display.

When I look at older mappings I see class/type values for non-RDF vocabs that look like this:

![Image](https://github.com/t3-innovation-network/desm/assets/658047/f94538a7-14bc-4dce-8df5-ec469ecda47b)

"Assertion" is the value that should be displayed.

**Comment by excelsior** [comment]
@philbarker I implemented the suggested fix for non-RDF schemas.

**Comment by philbarker** [comment]
Thanks @excelsior , looks good.
