### ISSUE TITLE
Define transformations

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#448]
A mapping predicate of transformed can very useful in showing when data from different parts of one model needs to be combined in order to map to another, but we should allow the transformations to be represented in a machine actionable notation (the different notations would be suitable for different modeling frameworks / execution environments).capturing the relationship between the abstract class and mapped schema classes in the domain being mapped may be worth investigating.

**Comment by philbarker** [comment]
See https://github.com/t3-innovation-network/desm/issues/404#issuecomment-2166949210 for a solution that encompasses this.

**Comment by philbarker** [comment]
@edgarf @philbarker @jgoodell2 

This issue is directly rated to issue #448 (also tagged as Data Transformation).  Shouldn't these issues be merged?  

It has been discussed during mutliple project team meetings and [documented with project team notes ](https://docs.google.com/document/d/16_-t7I-St8OjdJQeHfhfCP5SzgOXwjSH-h9dwkR1PIs/edit )and via [DESM Transformations to Support](https://docs.google.com/document/d/16aNbnAVg4SnJJegjTiZttQAHrqR8TAsUxc-CJOZgrOc/edit#bookmark=id.lgrxjzl6ocms).  

During our most recent meeting on June 13, 2024.  The following was documented. 

SOLUTIONS AND NEXT STEPS

- Instructions for scoping guidance are necessary and implementing a mapping is to provide the data needed for a third-party transformation tool.
- Mappers need to know they have to upload all properties within a given path.
- The mappers need to know if there always needs to be a reverse path/transform.
- The tool needs to allow two fields for paths as shown with Jim’s mockup [DESM Transformations to Support](https://docs.google.com/document/d/16aNbnAVg4SnJJegjTiZttQAHrqR8TAsUxc-CJOZgrOc/edit#bookmark=id.lgrxjzl6ocms).
- The 1st box is the (left) transform to the spine ← 
- The 2nd box is transfer from the spine →
- Provide users the syntax to utilize.  Either of these can be used.   Ideally the tool should validate the syntax so as not to end up with GIGO.  If validation cannot be achieved initially, the tool needs to show the two examples. 

$spine.person.firstname=$mapped.person.fname
or with some bracketed thrown in
$spine.['Person']['First Name']=$mapped.['Identity']['Name']['Given Name']


![Image](https://github.com/t3-innovation-network/desm/assets/20917206/9f5a90f1-50d3-4a93-802e-a6f7263fd2eb)

![Image](https://github.com/t3-innovation-network/desm/assets/20917206/edb355db-5c7d-413c-a25c-764786f98a12)

**Comment by jeannekitchens** [comment]
@edgarf isn't this supposed to be the transform issue being wrapped up?  Shouldn't it be under in process column?

**Comment by philbarker** [comment]
Yes, this is the issue that PR #404 should reference.

That implements the two boxes for inputting the forward and backward transformations respectively, which looks good.

However the information is displayed as a path, which is incorrect. I see we didn't specify how it should be displayed, let's put it under a heading of "Data Transformation"

We also didn't specify how to export the information. Lets hold on that as we need to sort out some other things in the mapping.

**Comment by philbarker** [comment]
Information is now displayed under an appropriate heading. 

Adding transformation information to the outputs will be addressed under a separate issue. (#582)
