### ISSUE TITLE
Namespace URIs for DESM 

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#449]
Currently we use https://desmsolutions.org/ns/ as the base URI for concepts (mapping predicates and abstract classes) in DESM mapping and for the terms used in the output.

Nothing exists at the URI, and as far as I can tell desmsolutions.org is not currently registered to anyone.

So far I've been happy to ignore this, those uri-like strings still work as dumb identifiers even if there is a danger of someone else using them for something different. But as more  projects use DESM it becomes important that we control the namespace URI and desirable that we put something useful there.

Assuming we are happy to use https://desmsolutions.org/ns/ we need to buy the domain. Otherwise we should create a permanent URI that redirects a domain we control. I would try something under https://w3id.org/ . In the long term the latter may be a preferable solution, but it is not backward compatible and I guess it would require some rewriting of code at least for the data output. So probably the former is the way to go.

BTW, I do not think that abstract classes should use that namespace, they should use something under the control of the project that is using them.

ref tracking issue issue #445

**Comment by jgoodell2** [comment]
Looks like desmtool.org is also available.

**Comment by philbarker** [comment]
On a further check, desmsolutions.org is owned by the Chamber, but there are no DNS records for it.

desmtool.org and desm.org are for sale, yours for ten quid.

**Comment by jeannekitchens** [comment]
@edgarf @excelsior @science @philbarker @jgoodell2 back in Sept 2020, Chamber purchased the domain as requested by Stuart and Joe and responded. I know this is documented in DESM notes and here's the email.  The email chain goes on with Joe letting Chamber know that once the production environment was set up the Chamber would be notified to set up the DNS and the Chamber replied to say the Chamber tech team would have to be brought in to set up DNS from their account. 

Hi Joe and Team,

Our web team bought the domain for DESMsolutions.com and DESMsolutions.org (we should use .org moving forward) . To start using the domain name, my colleague will need the CNAME or A record where you want to point the domains. Please advise and I will respond to my colleague and include you on the email in case she needs additional info. 

Best,
Joshua Westfall

**Comment by philbarker** [comment]
Resolution
- [ ] @philbarker to chase Taylor to get https://desmsolutions.org/ns/ so that it can host vocan defintion files

**Comment by learningtapestry-archive2** [comment]
@philbarker this task has no "Documentation" tag, as it's not technically a documentation, but also it's not something for LT to do, so for now, we just keep this on the side. Correct?

**Comment by philbarker** [comment]
@learningtapestry-archive2 agreed.

**Comment by philbarker** [comment]
@edgarf we now have https://t3-innovation-network.github.io/desm/ published from the /docs folder of the main branch of the repository. It has the DESM vocab definitions in https://t3-innovation-network.github.io/desm/ns

In order to publish these to https://desmsolutions.org/ns/ it is necessary to configure it as a custom domain, as documented here: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site  It's not a big job (at least I didn't find it so when I did for a site of my own), but needs access to the DNS configuration which I think you have?

**Comment by excelsior** [comment]
@philbarker I think Edgar is right, we need access to the desmsolutions.org domain which we don't have.
