### ISSUE TITLE
Can upload new abstract domain classes after config, but to no effect.

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#450]
Aftrer creating and activating a profile I realised I needed to add an abstract class. The config let me do this, so as admin I see:
![image](https://github.com/t3-innovation-network/desm/assets/658047/f4967f2b-647e-47ee-8afe-dba2084eb261)

But the newly added class is not visible to mappers, they see:
![image](https://github.com/t3-innovation-network/desm/assets/658047/b3495584-afa1-41a4-8c61-4d4eeb5467b7)

(They don't see the new micro-credential specification class)

**Comment by jeannekitchens** [comment]
@philbarker agree to move this to priority 1.

**Comment by philbarker** [comment]
Resolution (as with issue #458 )
- [ ] it should be clear when an update is applied successfully to the data stored. Explicit "save" buttons would help.
- [ ] the admin interface should reflect the data actually in the database.

**Comment by edgarf** [comment]
- For saving process, we will just make the whole messaging more prominent, because replacing the mechanism from being async to "save on demand" would be a big change at this time. 
- When somebody imports a different set of Abstract Classes, we will a) add new b) update existing c) remove those classes that don't yet have a mapped spine.

**Comment by philbarker** [comment]
@edgarf @shlag3n 

I have confirmed the following works
- Adding a new abstract class.
- Deleting an abstract class that has no spine
- Not deleting a class if it is not in the new concept scheme but is present in the config and there is a spine.

However, in this last case there is a message that says "All changes saved" .... which they I think weren't ... and the "origin URL" is shown as being the URL for the file without the abstract class, so there is a mismatch between the file that the config screen says is being used and the abstract classes in the profile.

Question: what would happen if changed the URI `@id` of a class but nothing else? If it is counted as deleting the existing abstract class and adding a new one, I would be happy. Let me know if the behaviour is other than this and we can document it.

Please: 
- [ ] When a class cannot be deleted, treat this a failure to upload. Display a message that says which class cannot be changed. Make sure the Origin URL reverts to the old value.

**Comment by shlag3n** [comment]
@philbarker re your question - current class will be updated with new @id.

About the case when class cannot be deleted - if we had "origin url 1" with ac1, ac2, ac3 (have spine) and uploading "origin url 2" with ac2, ac4 the current result will be "origin url 2" with ac2, ac3, ac4 and message "All changes saved" will be shown, is it correct that we need to change that behavior and revert all changes so the result should be "origin url 1" with ac1, ac2, ac3 and error message should be shown?

And we need to have the same processing for predicates, right?

**Comment by philbarker** [comment]
@shlag3n 
> re your question - current class will be updated with new @id.

I'm not sure how you would know that an abstract class uploaded is in the current set of classes if it has a different `@id`? Is DESM matching on the label? That would mean that it would be impossible to fix errors in the label.

> About the case when class cannot be deleted - if we had "origin url 1" with ac1, ac2, ac3 (have spine) and uploading "origin url 2" with ac2, ac4 the current result will be "origin url 2" with ac2, ac3, ac4 and message "All changes saved" will be shown, is it correct that we need to change that behavior and revert all changes so the result should be "origin url 1" with ac1, ac2, ac3 and error message should be shown?

Good question. I think for simplicity the answer has to be "Yes". I can't think of any other way of keeping the info in the origin URL and in the system in sync, which is desirable, and may be necessary when we get the linked data output fully working.

**Comment by shlag3n** [comment]
@philbarker sorry re @id - was talking about id for the set as about single class - yes, previous will be removed, new will be created.

as about other things - will fix/update them and let you know when they will be deployed.

**Comment by philbarker** [comment]
Looks good to me.
