### ISSUE TITLE
Regexp for phone numbers is too strict

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#451]
Trying to activate a new profile I get the  error message 

> Attention: ["The property '#/standardsOrganizations/0/dsoAgents/0/phone' value \"+44 7879 339153\" did not match the regex '^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$' in schema 2e3fda39-b98b-5b7b-b600-137ff0d6b9ae#"]

1. many people don't bother with space separators in the phone numbers, e.g. +44 7879339153
2. not all phone numbers confirm to that pattern, e.g. UKR has a 3-digit international prefix +380; some UK area codes are 3-digit, some are 4- or 5-digit.

Also:
there is no information on the entry screen for DSO mapper information about the format required or whether the number enters conforms: you only get the that error message if you know to go to the config profiles screen and try to activate a profile.

To fix:
relax the regex requirement and say what format is required on the data entry screen; optionally use JS to check what is in the box.

I suggest an optional Int code preceded by `+` and the rest with no separators: `(\+\d{1,3}\s)?\d{9,11}`

**Comment by shlag3n** [comment]
@philbarker, @edgarf  not sure how this number will be in use but it may be hard to make a call without knowing international code. There are some libraries based on https://github.com/google/libphonenumber that we can use if we are ok to ask provide international number, with default configuration numbers like "+44 7879 339153", "+44 7879339153", "44 7879 339153" and all other variations will be accepted. Also we will have human error on validation failure (general message without regular expression) and be able to output numbers in the same format/know country/etc. What do you think?

**Comment by philbarker** [comment]
@shlag3n tbh, I don't think it will be used very often at all, and when it is used there should be other information that could be used to figure out where the organization is. Fixing spurious errors from stopping activation of profiles is high priority, but other than that details of the fix are low importance. 

So I would be happy with an optional `+` followed by a reasonable length of digits and spaces: for example check against the regex `^\+[0-9 -]{6,18}$`

**Comment by shlag3n** [comment]
@philbarker, got it, thank you for explanation. Going to use ` /^\+?[0-9 -]{6,18}$/` to relax on `+` and will add description as "Phone number should be at least 6 characters long and can contain digits, spaces, or hyphens, optionally starting with a plus sign. Examples: +1234567890, 123-456-789, 123 456 7890", error message will be the same but with new regex. Will it work?

**Comment by philbarker** [comment]
Looks good. 
Checked on https://gopher.desm.staging.c66.me/dashboard/configuration-profiles/45
I can't check every possible combination of digits and spaces that makes a valid phone number, but now works with UK and Spanish forms, and I get a sensible error message for those that don't work which doesn't stop the user being created.
