### ISSUE TITLE
Deleted organizations aren't really deleted

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#458]
(tested so far only on active config profiles)
When I add and then delete DSO, for example I added and then deleted DSO3 on the Demo and Test instance, config UI looks fine:
![image](https://github.com/t3-innovation-network/desm/assets/658047/f5db0b77-1b0e-4952-a340-aef2a9ab8da2)
--just the two DSOs.

but when I go to view mappings and show spine specifications the deleted DSO (and others) is shown

![image](https://github.com/t3-innovation-network/desm/assets/658047/1ed00dd5-46f5-4385-ab93-de7311505f7a)

I think this may have been behind the issue getting Nate Otto added the other day: no one seemed to be added with that email and yet it seems that in the database there was an account with that email.

Resolution seems similar to issue #450:
- [ ] it should be clear when an update is applied successfully to the data stored. Explicit "save" buttons would help.
- [ ] the admin interface should reflect the data actually in the database.

**Comment by philbarker** [comment]
@shlag3n I don't like the sound of losing mappings, even though the most common circumstance for deleting an organization is when they don't do any mapping. Can we have don't allow removal if there are mappings, but do allow renaming of the Org?

**Comment by shlag3n** [comment]
@philbarker yes, we can. Should we remove agents in this case + is it about mappings in all statuses or only completed ones?

**Comment by philbarker** [comment]
Don't allow removal of an Org with any mapping, whatever the status, or with any mappers: let the user know that they need to remove these first. (Though we do have the problem at the moment that an admin user cannot do this, that will be fixed.)

Don't remove mappers or mappings if the Org is just renamed.

**Comment by philbarker** [comment]
@shlag3n 
I cannot test this because whenever I try to add an organization to an existing profile (in order to delete it again and check that it comes and goes as it should) I get an error:

![Image](https://github.com/t3-innovation-network/desm/assets/658047/b0bcd1ca-2298-4f68-96f9-3e4a464cf984)

This is on the DESM Demo and Documentation profile <https://gopher.desm.staging.c66.me/dashboard/configuration-profiles/39>, logged in as phil.barker@pjjk.co.uk (admin), but also got similar on PhilTest1 <https://gopher.desm.staging.c66.me/dashboard/configuration-profiles/15> and Phil SDO-DCMI <https://gopher.desm.staging.c66.me/dashboard/configuration-profiles/22>

**Comment by shlag3n** [comment]
@philbarker it'll work only for new profiles as existing ones contain inconsistent data, we will need to write migration to fix that. (cc @edgarf)

**Comment by shlag3n** [comment]
@philbarker @edgarf migration fix was implemented and applied on staging. Also adding new organization was fixed too (it was unrelated to data inconsistency).

**Comment by philbarker** [comment]
Testing: logged in on gopher as phil.barker@pjjk (admin) using demo and doc profile, added new DSO call Delete me. 

(Aside, issue #488 occurred here)

Log out, view shared mappings, can see "Delete me" in list of spine specification.

Log back in as admin, 
try delete the "delete me" org while it still has a user: cannot -- good.
Delete the user for that org, and then can delete the "delete me" org -- good.

Log out, view shared mappings, cannot see "Delete me" in list of spine specifications.

All looks good as far as this issue is concerned, moving to QA Passed. Thank you @shlag3n
