### ISSUE TITLE
Fix Alerts/Remove Tooltips&Bootstrap JS

### ISSUE THREAD

**Issue by shlag3n** [t3-innovation-network/desm#466]
- [ ] 1. remove dismiss-ability for UI elements that are not actually alerts but static part of UI
- [ ] 2. change alert component to be reactive and remove errors on close
- [ ] 3. remove bootstrap tooltip attributes as they are not working anyway (titles are working)
- [ ] 4. remove jquery/bootstrap + maybe popper from js bundles if they're not in use

**Comment by edgarf** [comment]
@philbarker, the whole error alerting set-up in DESM requires updates to work properly system-wide. We extracted this sub-item issue and added separately. I'm putting it into Ready/P1, because it will be required for multiple tasks.

**Comment by philbarker** [comment]
@edgarf  I am not sure what to look at to test that this is resolved. Looks like a back-end thing, so if you're happy it is resolved move it over.

**Comment by edgarf** [comment]
Thanks, sounds good. Yes, it was more of a backend task, to update all the behind-the-scenes for the error/warning flash messages
