### ISSUE TITLE
No schema name on mapping display

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#470]
The schema name should be displayed when the mappings are viewed:
![image](https://github.com/t3-innovation-network/desm/assets/658047/e10b9fca-a8a0-479e-90f6-a6ab9b5a3ffb)
(this from https://desm.credentialengine.org/mappings-list?abstractClass=Assertion )

The schema name and (optionally) the version are entered when the schema is uploaded. These should be displayed where the red circles are.

**Comment by philbarker** [comment]
- [ ] display schema name and version.

**Comment by philbarker** [comment]
Checking on gopher, as phil+sdo@pjjk (mapper) on PhilTest1 profile
on https://gopher.desm.staging.c66.me/mappings-list?abstractClass=Location I see no schema name and version

![Image](https://github.com/t3-innovation-network/desm/assets/658047/4bf6d830-7787-49c3-bbbb-2c52e6c5e6f1)

Also don't see it on view shared mappings, https://gopher.desm.staging.c66.me/mappings-list

![Image](https://github.com/t3-innovation-network/desm/assets/658047/add36f5b-666c-4ef6-aa32-a2f5abe89e8b)

moving back to in progress.

**Comment by shlag3n** [comment]
@philbarker sorry, there were some issues with deployment. Redeployed, checked that changes were applied - ready for QA now.

**Comment by philbarker** [comment]
that looks better! Thank you @shlag3n
