### ISSUE TITLE
Fix mapped terms removal/updates on partial mapping via dialog

### ISSUE THREAD

**Issue by shlag3n** [t3-innovation-network/desm#476]
- [x] 1. Fix mapped properties removal (currently no actual removing if all properties will be unmapped on saved mapping)
- [x] 2. Update behavior on selecting No Match (connected terms should be removed)
- [x] 3. Don't save partial mapping changes to DB via dialog except comments

**Comment by philbarker** [comment]
@shlag3n 

Tested on gopher, using login phil+dcmi, profile PhilTest1, as before.

I can now delete the mappings, and have deleted them (which was the problem mentioned in [this comment](https://github.com/t3-innovation-network/desm/issues/472#issuecomment-1991534935))

So on https://gopher.desm.staging.c66.me/mappings/47/align I see 


![Image](https://github.com/t3-innovation-network/desm/assets/658047/5d1fdea0-1524-4b77-9b6b-b0cf0b279270)

and on https://gopher.desm.staging.c66.me/mappings/217/align I see


![Image](https://github.com/t3-innovation-network/desm/assets/658047/87a16d5c-0ba4-4c86-9ce9-bfc21ffb5a91)



However, I still get this error message when I try to "Abstract" delete from the spine


![Image](https://github.com/t3-innovation-network/desm/assets/658047/edb9aa93-f31f-4c05-9ace-4cb28b08e874)


I cannot see any corresponding alignments in any of the mappings mentioned there. (I'm pretty sure at least one of them never had that term mapped)

**Comment by philbarker** [comment]
looks good, can now delete a spine term once all property mappings involving that term have been removed.
Thank you @shlag3n , moving to QA Passed
