### ISSUE TITLE
The schema output data currently does not include a confidence value (%)

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#52]
@richard0000 & @jbaird123, the display frames for a mapping show a confidence value expressed as a percentage. That % information is currently nowhere in the data. It should be a value in the [desmMappingPredicate.json](https://github.com/t3-innovation-network/desm/blob/master/concepts/desmMappingPredicates.json) SKOS file.

**Comment by stuartasutton** [comment]
@richard0000, the [desmMappingPredicate.json](https://github.com/t3-innovation-network/desm/blob/master/concepts/desmMappingPredicates.json)) SKOS file has been updated with a `weight` property for assigning a weight to each concept for calculating the alignment score (%) in the display of the mapping.

Here are the instructions I got from Nate at Credential Engine:

>For instance:
>
>On the Person tab, there are 5 organizations being aligned to the spine. The highest possible weight is 5. So 5 * 5 = 25, which is the maximum possible score for any set of alignments on the Person tab (i.e., a set of alignments where all of them are Identical).  The first set of alignments has weights that add up to 20.  20 / 25 = 0.8 and 0.8 * 100 gives us 80%. (Incidentally, this kind of math is why clarifying how qdata:percentage works is important).
>
>On most tabs, the highest possible score is 25.  The Competencies tab has 6 organizations being aligned to the spine, so its highest possible score is 30.
>
>Another example: On the Competency tab (maximum possible score of 30), the alignment for Competency Framework Title has a total weight of 22.  22 / 30 = ~0.73333 (repeating) * 100 = ~73.3333 (repeating)% which gets rounded up to 74%

**Comment by richard0000** [comment]
@stuartasutton the mentioned file is not updated. Could you review it, please?

**Comment by stuartasutton** [comment]
I updated the file earlier but may not have commuted it. I'll check as soon as I get home.

**Comment by stuartasutton** [comment]
Corrected: https://github.com/t3-innovation-network/desm/blob/master/concepts/desmMappingPredicates.json

**Comment by richard0000** [comment]
Covered with PR #64
