### ISSUE TITLE
Issue with Storing and Displaying Definition Encoding

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#529]
The encoding that's being displayed with definitions is a human and machine readability issue.  If the encoding is a result of it being included with the uploaded files, that needs to be stripped by DESM. I feel it has to be prioritized.  It doesn't make sense to retain encoding that serves no purpose and that gets in they way of readability and has no use for the machine readable files. It would require data users to strip it out and makes looking at a making appear broken.  This came up during a mapping review this morning with @philbarker , me, and mappers participating with the mapping linked below. 

Take a look at the real mapping for the Global Micro-Credential Mapping for human readability and machine readability. https://desm.credentialengine.org/mappings-list

Below is a screen shot...there are many examples.  

Also, is the defintion set to a character limit?  A download of the machine readable files that include defintions with html where the definition is cut off as seen in the screenshot below needs to be reviewed to see if data is missing completely or only missing from the UI 

![image](https://github.com/t3-innovation-network/desm/assets/20917206/db97d12c-3b9f-4eb7-b9eb-5790f4d0dfe2)

![image](https://github.com/t3-innovation-network/desm/assets/20917206/cd323497-1e26-4d7a-bf32-46fcc2a7c533)

**Comment by excelsior** [comment]
@jeannekitchens 
The problem on the second screenshot is caused by the fact that language map values can be represented in different formats, and our parser didn't support all of them. I improved the parser.

The question is how would you like this data displayed? In the example above, the `Endorsement` property has three definitions in English. Should they be displayed as a list (bulleted or numbered) or just as three paragraphs of text? What if the values are in more than one language? Should the language code be displayed, too?

**Comment by jeannekitchens** [comment]
Bullets would be helpful. I wouldn't recommend numbering.  If there are languge codes, that could be helpful but with the machine readable version, do we identify the language of the descriptions?

**Comment by philbarker** [comment]
@excelsior @jeannekitchens +1 to bullets

**Comment by excelsior** [comment]
@jeannekitchens @philbarker There was no such problem on staging, I believe. So I exported the Microcredential Mapping profile from CredReg and imported it to staging. I can test the fix there:

https://gopher.desm.staging.c66.me/mappings-list?cp=47&abstractClass=Assertion

**Comment by philbarker** [comment]
There are some things that look odd now. For example, look at the "Issuer" property on [Assertion](https://gopher.desm.staging.c66.me/mappings-list?abstractClass=Assertion&cp=47) It appears three times for each schema in the mapped properties column. I don't recall that. 

Also the spine property for "Issuer" has "W3C Verifiable Credential" and I am sure it was added from ELM.

Can you roll back to what it was before and check?

**Comment by philbarker** [comment]
Issue in above comment has now been fixed.
