### ISSUE TITLE
Question about showing person information on mappings

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#542]
I see this is added to the public mapping screen:

![image](https://github.com/t3-innovation-network/desm/assets/658047/8ce89188-fce5-464b-918d-58a4fc0728dd)

(This image from https://tool.desmsolutions.org/mappings-list?cp=1&abstractClass=Competence )

Is there a reason for showing this information? I've seen it on staging and assumed it was some debug info, but now it is showing on the T3 instance. I'm kind of wary about showing any personal information without good reason.

**Comment by jeannekitchens** [comment]
@philbarker @edgarf I think it's useful to include the specification names and laste updated dates. Otherwise, it's not possible to know how dated or not a mappigng is.  Remove the names of the mappers though.

**Comment by philbarker** [comment]
OK, show the Specifications and Dates, but can we please **make sure it is the specification names** and versions (not the organization of the mapper) that displays. And there is no need to show the abstract domain being mapped. It looks like currently every update is being shown, we only need the latest update.

The names of the specifications and versions should also be what shows in the "show alignment specifications" drop-down (currently it too shows the organization):

![image](https://github.com/t3-innovation-network/desm/assets/658047/98d57c0d-791f-403f-a581-92f99d137264)

**Comment by excelsior** [comment]
@philbarker The current format is `<Organization> (<version>) updated on <date>` or `<Organization> updated on <date>` if there's no version.

**Comment by philbarker** [comment]
can we please make sure it is the **specification names** and versions (not the organization of the mapper)

**Comment by philbarker** [comment]
@excelsior what is showing on the Cred Eng instance is still not right.

It shows this:

![image](https://github.com/t3-innovation-network/desm/assets/658047/bd1f9de4-072b-4b71-b97d-b1390e2931c0)

To repeat here what I said on slack:
"The drop down should only show the alignment specifications for the **abstract domain** and project being viewed.  This is what shows for the "Shared mapping list". It'll be the same specifications showing in the drop down as show in the list of specifications mapped."

Look at https://desm.credentialengine.org/mappings-list?abstractClass=Micro-credential+Claimed&cp=6
All the specification names are showing in the drop-down, even though only one is available in the mapping for this abstract class.
I don't understand why you would show options in a drop down for which no mappings can be shown.

**Comment by philbarker** [comment]
PS. if we can have the dates for the last-update of the mappings back, that would be great too.
