### ISSUE TITLE
Info on the spine terms when viewing mapping is misleading

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#553]
The latest version to be rolled out has info on the spine term that looks like this:
![image](https://github.com/t3-innovation-network/desm/assets/658047/cfcf3237-4d9e-49f2-bbd8-d1af3f1fa7dd)
(taken from https://desm.credentialengine.org/mappings-list?cp=6&abstractClass=Assertion )

This is conflating the spine term with the mapping as it references schema that are only mapped to it.  Also, as we recognise how "organization" is being used it becomes less relevant to spine terms. 

Can we change this to

- Property Name
- Definition
- Origin

**Note** 
Property Name: please preserve the case of the original property name (because in ELM `Evidence` is a class and `evidence` is a property).
Origin should be the schema from which it was added to the spine.

**Comment by philbarker** [comment]
Checked with https://gopher.desm.staging.c66.me/mappings-list?abstractClass=Organization&cp=45

Looks good now: all show the name (and version where one exists) of the schema from which the spine term was added.

**Comment by AH1CEDS** [comment]
@edgarf , I used Alexandra(SDO)@schema.org user to look at the shared mappings for 3 different “current configuration profiles” (https://tool.desmsolutions.org/mappings-list?abstractClass=Competence&cp=1, https://tool.desmsolutions.org/mappings-list?abstractClass=Rubric&cp=9, and https://tool.desmsolutions.org/mappings-list?abstractClass=Organization&cp=13). For the first two, as Phil commented on his QA in the staging environment, the Origin correctly shows “the name (and version where one exists) of the schema from which the spine term was added.” For the last one (“Demo & testing” profile), the Origin was blank for some of the items with 0% progress, but said “test” for another item, also with 0% progress (see screenshot below).

One additional note: Phil’s initial comment on this issue from June 12 asked to change the headings to Property Name, Definition, and Origin. Current headings are Element/Property, Definition, and Origin. 

![image](https://github.com/user-attachments/assets/3681b207-9832-49d4-a84f-2b4671cfcd4b)

**Comment by excelsior** [comment]
@AH1CEDS,

I fixed the shared mapping page

1. The origins are shown for all properties.
2. The missing aligments are displayed.
3. The wrong heading has been renamed.

The changes are only on gopher (i.e. staging).

**Comment by dlawsonQIP** [comment]
Verified spine terms on Gopher staging. Correctly shows headers as Property Name, Definition, and Origin.

**Comment by philbarker** [comment]
Looks good on Credential Engine, we can close this.
