### ISSUE TITLE
Fix filter dropdowns on shared mappings page

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#562]
There is some UI issue that stops the lower items in the drop-down lists from being selected

To reproduce:
1. go to https://gopher.desm.staging.c66.me/mappings-list?abstractClass=Organization&cp=45
2. put the cursor over any of the filter drop-downs (e.g. show spine specifications, show alignment specifications, show alignments) and a list of check boxes will drop down.
3. move the cursor down to the bottom of the list in an attempt to deselect what is there.

Expected behaviour: the drop-down stays put so that you can alter the check box
Observed behaviour: the drop-down closes stopping you from access some of the check boxes

**Comment by excelsior** [comment]
Fixed as part of #424.
