### ISSUE TITLE
People registering with the DESM need to identify themselves and the SDO they represent

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#6]
In registering with the DESN tool, people need to identify themselves with  the following:

1. Full name
2. Email address
3. Name of Standards body represented
4. Verification email address (email of person authorized to approve the the registrant for mapping the SDO's specifications)

**Comment by jeannekitchens** [comment]
@jbaird123 is there any role management?  Are all users read/write/delete for their organizations and/or is there an admin role to approve accounts?  Where else might we need to determine if a user role is applicable (e.g., committing a mapping so it's public).  How should we cover these topics with the upcoming agenda and between with these issues so we don't hold up the work?

**Comment by richard0000** [comment]
@stuartasutton 
> In registering with the DESN tool, people need to identify themselves with the following:
> 
> 1. Full name *(Is this one only field or 2 separate (first name and last name)?)*
> 2. Email address
> 3. Name of Standards body represented *(Do we offer a list of options for it? Which would be the values?)*
> 4. Verification email address (email of person authorized to approve the the registrant for mapping the SDO's specifications) *(Do we suggest any email?)*

**Comment by stuartasutton** [comment]
@richard0000, as a follow-on to Jeanne's comment above (https://github.com/t3-innovation-network/desm/issues/6#issuecomment-661003492), the real entities with power to enter mappings are the SDOs who delegate that power to individuals which indicates that there are registered SDOs related to individuals with various levels of read/write/delete privileges.

**Comment by jeannekitchens** [comment]
Full name (Is this one only field or 2 separate (first name and last name)?)  Yes.
Email address
Name of Standards body represented (Do we offer a list of options for it? Which would be the values?) It we offered a list, we'd need to have an admin role that can populate it.  Likely, that wouldn't work.  It would be a string field to support the organization's name. 
Verification email address (email of person authorized to approve the the registrant for mapping the SDO's specifications) (Do we suggest any email?) It really should be an email account with the standards domain.  Please note that the data standards organizations should set up the account with an email using their domain (e.g., xxxx@credentialengine.org) and they will need to be able to add users to the organization.  These users are often third parties that do not use the data standards organization email.  They will need to add these persons to do the actual mapping.

**Comment by jbaird123** [comment]
@stuartasutton @jeannekitchens - We're trying to keep this as simple as possible and add complexity only when needed.  This is what we understand is needed given the small number of users we expect on this site:

1. Users cannot register themselves directly (we don't want just anyone being able to create an account).
2. There will be only 2 roles: Website Administrator,  Regular Users
3. Web Site administrators will have the (at a minimum) the following capabilities: Create / Modify / Delete organizations.  Create / Modify / Delete users (and associate those users with an organization).  Create / Modify / Delete website administrators.
4. Regular Users will be able to upload specifications and perform the mapping functions.

**Comment by richard0000** [comment]
Issue covered with Pr #11
