### ISSUE TITLE
Question: Notifications of changes to current mappings

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#60]
@jbaird123, @richard0000 & @jeannekitchens, I know that Joe is working with the Joshua with regards to using any messaging system the Chamber has deployed as the means of sending notifications of changes to other standard development organizations (SDOs) in a "mapping set".  While a **Phase 3 matter**, we need to think about organizations other than SDOs subscribing to the notification service. For example, an organization like Eduworks will want to enable its metamodel interchanger functionality to "listen" for such change notifications in order to keep its interchanger services current.

Thoughts?

**Comment by richard0000** [comment]
PR #75 under review

**Comment by richard0000** [comment]
Covered with PR #75
