### ISSUE TITLE
Selecting multi-domains on loading a schema document for an abstract class

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#62]
@jbaird123, @jeannekitchens, @richard0000:  

At loading a schema document, we usually need to select multiple domains (classes) defined in that schema for mapping after the schema document has been ingested. 

We are using the term "domain" in two different ways in the tool:
1. **Abstract domains**:  Abstract classes that have been defined in a SKOS file that identifies the types of abstract entities being mapped--e.g., "Credential", "Competency", "Course", "Organization".
2. **Explicit Domains**: Explicit class(es) as defined in the property definitions as the property's `rdfs:domain`. 

This particular issue is about the explicit domains of individual properties to which those properties "belong".  We can see this multiplicity demonstrated in the original wireframe below for the abstract class "Person" for an HR Open mapping. The `rdfs:domain` of each HR Open property has been explicitly included in the schema being mapped to the spine--`PersonNameType` and 'IdentifierType` circled in red.  A property may also have multiple domains.

*The spine properties should have the same treatment.*

Ricardo and I discussed this issue on our 1-to-1 zoom session on Wednesday and he thinks he has a way forward. 

<img width="1583" alt="Multi-Domain_DESM" src="https://user-images.githubusercontent.com/2939046/100520216-85b0ca80-3151-11eb-8c7d-1ee08e21dc59.png">

.

**Comment by richard0000** [comment]
Resolved with PR #61
