### ISSUE TITLE
Include value of domain with properties in mapping viewer

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#68]
In the wireframe display of properties being mapped, they include the domain as circled below. This is very handy when a array of properties come from different classes--in the example from a `PersonNameType` and `IdentifierType`. While the wireframe does not show the domains of the properties in the spine, it really should.  

<img width="1342" alt="DESM-domain_included-2" src="https://user-images.githubusercontent.com/2939046/101093075-197a0080-356f-11eb-95c8-c0f066f40c63.png">

Image from wireframe: https://marvelapp.com/prototype/adf7283/screen/68220202

**Comment by stuartasutton** [comment]
However, I would switch the order so that the property is first; e.g. "middle [PersonalNameType]" as opposed to "PersonalNameType middle"

**Comment by richard0000** [comment]
PR #73 under review

**Comment by richard0000** [comment]
Covered with PR #73
