### ISSUE TITLE
Every spine sorting criteria and alignment sorting criteria to have a detailed description of how should work.

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#71]
The sorting criteria in the mockups are not described. It's necessary for development purposes to have instructions on how should each of the options work. See screenshot below:
![sortoptions](https://user-images.githubusercontent.com/6996951/101698858-fb257080-3a58-11eb-9e73-b3fdb00bfac0.gif)

**Comment by stuartasutton** [comment]
@richard0000, I spent some time reviewing Nate Argo's sort function and have them all figures out except for "Sort data order" on the "Sort Aligned Items By". I have a question out to Nate.

**Comment by stuartasutton** [comment]
@richard0000, drop the "Sort data order" from "Sort Aligned Items By" listing. The data in Nate's viewer was taken from spreadsheets..."Sort data order" references the order of the columns in the spreadsheet. That is totally irrelevant for the DESM.

**Comment by richard0000** [comment]
PR #73 Under review

**Comment by richard0000** [comment]
Covered with PR #73
