### ISSUE TITLE
Logic to assign colors for alignment predicates

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#72]
# Overview
Looking at the wireframes, we can see the predicate labels in colored boxes. The color varies between the different labels. There is no indication of how should the colors be applied to the different predicate labels.

![image](https://user-images.githubusercontent.com/6996951/101776678-11bade80-3ad0-11eb-9eca-7afab4f1952d.png)

### Proposal 1
One logical thinking would be to add colors depending on the weight, that can be read from the skos file and at the moment of loading the "Synthetic Spine Property Mapping By Category" screen, is available as an attribute of each predicate object.

### Proposal 2
Another different way of achieving this would be to add a hexadecimal color code to the skos file, so we can read and use it by simply adding it to the "background-color" CSS rule.

### Proposal 3
We could avoid touching the skos file or even adding logic to it by simply hardcoding the color values in the predicates model now. This solution may work but need technical input for sure if we need to modify it. But this also can be included in the second stage so we can add it to the administrative dashboard as an option to let the users modify the color by selecting it from a color palette.

## Preferred solution and why:
**Proposal 3**. We can solve the issue rapidly and be perfectly prepared to let the user modify it when the administrative dashboard is implemented.

Please let me know your thoughts @stuartasutton.

**Comment by stuartasutton** [comment]
I agree that adding any logic to the SKOS file to handle this should be left to Phase 3 if done at all and could be part of  the functions of the administrative dashboard to allow the administrator to select colors after the mapping predicate SKOS file has been uploaded.

For now, here are the colors Nate's viewer provides:

<img width="2262" alt="Screen Shot 2020-12-10 at 2 26 25 PM" src="https://user-images.githubusercontent.com/2939046/101837779-6b350480-3af4-11eb-9d04-032c552213e8.png">

**Comment by richard0000** [comment]
PR #74 under review

**Comment by richard0000** [comment]
Covered with PR #74
