### ISSUE TITLE
Ingest of RDF files serialized in formats other than JSON-LD

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#79]
@richard0000, @jbaird123, @philbarker, @science, & @jeannekitchens 

I tried loading an RDF file serialized in RDF/XML (extension .xml) rather than JSON-LD with no success ("The provided value is not JSON"). The problem goes back to our longstanding discussion around whether we have focused the schema file ingest/parsing directly on the JSON-LD serialization or on the underlying formal schema as suggested by Steve and original decided--in this case on RDF Schema.  We will likely receive RDF files serialized as JSON-LD (.jsonld), RDF/XML (.rdf or .xml), Turtle (.ttl), N-Triples (.nt), RDF/JSON Resource-Centric (.json), and even RDFa (.xhtml)--all legitimate serializations of RDF.  The RDF schema and SKOS files from D2L currently come in RDF/XML, RDF/JSON Resource-Centric, Turtle or N-Triples and not in JSON-LD at all. 

Of course these non-JSON-LD serializations can be converted automatically to JSON-LD using publicly available conversion tools, but those conversions usually don't come with a context file and have full URI as opposed to prefixed namespaces which would also cause problems if the parsing is depending on full-fledged JSON-LD.

So, we shouldn't fail on ingest with any file that conforms to XML Schema, JSON Schema, and RDF Schema (all serializations).

**Comment by richard0000** [comment]
@stuartasutton since we tested the ingest of non JSON-LD files with one only example of each of the formats (XML, ZIP and CSV), we will need to see the file that failed, if it's possible, in order to resolve the bug.

Thanks!

**Comment by stuartasutton** [comment]
@richard0000 I am working on schema and concept scheme files now and will have a full set of all schema files from all the SDOs for the abstract class set that we have been using. As soon as I am finished with that today or tomorrow, we can pick examples from that array for RDF Schema, JSON Schema, XML Schema and CSV.

**Comment by richard0000** [comment]
@stuartasutton PR #81 could've fixed this issue. Could you please confirm? Thanks!

**Comment by stuartasutton** [comment]
@richard0000 it doesn't seem to work for me (see screenshot below). I have added a zip file here with my testing files. Note that the zip has four D2L ASN files for the **same framework** in the RDF standard serializations: .rdf (RDF/XML), .json (RDF Resource Centric), .ttl (Turtle), and .nt (N-Triples). I tested the ASN_D2695955.rdf file.

[ASN_D2695955.zip](https://github.com/t3-innovation-network/desm/files/5760602/ASN_D2695955.zip)

<img width="1149" alt="Screen Shot 2021-01-02 at 9 16 36 AM" src="https://user-images.githubusercontent.com/2939046/103462634-6faba200-4cdb-11eb-8a6c-fb90b9a6431b.png">

**Comment by richard0000** [comment]
@stuartasutton We've found 2 Issues:

1- Both RDF and JSON versions of the ASN specifications, lack of `rdfs:Class` nodes (nodes with `"@type": "rdfs:Class"`), as the tool is expecting.
Remember the tool will first try to have the files in a JSON-LD format, which in this case works for these 2 files, and then it will try to get all the `rdfs:Classes`, which at least needs one between the uploaded files.

**Comment by stuartasutton** [comment]
@richard0000, both files (.rdf) and (.json) are perfectly conformant with XML Schema and JSON Schema so neither should fail.  

## RDF Version

The RDF/XML file (.rdf) is fully conformant XML.  Nothing says that an entity in XML must be typed. The first entity in the file (`http://asn.desire2learn.com/resources/D2695955.xml`) is not typed, but all other entities are typed with statements like`<asn:StandardDocument rdf:about="http://asn.desire2learn.com/resources/D2695955">`. Note the `asn:StandardDocument` at the beginning of the phrase says I am of the type asn:StandardDocument. 

Here are two examples of how type might be legally expressed--the first being from the file that's failing:

```
<asn:StandardDocument rdf:about="http://asn.desire2learn.com/resources/D2695955">
        <asn:jurisdiction rdf:resource="http://purl.org/ASN/scheme/ASNJurisdiction/DCMI"/>
```
...also could have been written as `rdf:Description` instead of `asn:StandardDocument` with the type explicitly declared:

```
<rdf:Description rdf:about="http://asn.desire2learn.com/resources/D2695955">
        <rdf:type rdf:resource="http://purl.org/ASN/schema/core/StandardDocument"/>
        <asn:jurisdiction rdf:resource="http://purl.org/ASN/scheme/ASNJurisdiction/DCMI"/>
```

## JSON Version

The JSON version is in "RDF/JSON Resource-Centric" which is purely conformant JSON.  Again, there is no promise in a JSON file that all entities will be typed.  So this file conforms to **JSON Schema**.  The first entity in the file (`http://asn.desire2learn.com/resources/D2695955.xml`) is not typed, but all of the others (framework and competencies) are typed using the full URI--just not with a prefixed `rdfs:type`:

```
"http://asn.desire2learn.com/resources/D2695955": {
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": [
            {
                "value": "http://purl.org/ASN/schema/core/StandardDocument",
                "type": "uri"
            }
        ]
```
...and

```
 "http://asn.desire2learn.com/resources/S2695991": {
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": [
            {
                "value": "http://purl.org/ASN/schema/core/Statement",
                "type": "uri"
            }
        ]
```

**Comment by excelsior** [comment]
@stuartasutton I added Turtle and N-Triples support. Please notify me if you're interested in other RDF formats as well (i.e. N-Quads, Notation3).

Also, just to clarify what Ricardo said: we only support zipped JSON schemas. Uploading ZIP archives containing files of other formats doesn't work. Let me know if you need the ability to upload archives with arbitrary file formats.

**Comment by stuartasutton** [comment]
@excelsior, sorry about the zip misunderstanding. I wasn't expecting it to be uploaded into DESM. I just used the zip to bundle up the various serializations of the same framework so you all would have them. 

I do **not** think that handling N-Quads or Notation3 are necessary. We do need to be able to handle RDF/JSON Resource-Centric (precursor to JSON-LD). While no longer favored since the arrival of JSON-LD, there are large pools of RDF/JSON out there. The largest registry in the prototype (D2L's ASN) has not converted from RDF/JSON to JSON-LD.

**Comment by richard0000** [comment]
Covered with PR #84 

@stuartasutton besides all the changes performed, please note that the last RDF file you shared for ASN, had an issue in lines 24 and 25. I tried removing those lines, and the tool processed the file correctly.
