### ISSUE TITLE
Use T3 Logo and Style Guide

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#8]
Use the T3 logo and style guide for the DESM application:

Colors:
Navy Blue—R:0, G: 58, B: 93
Gray
White (when on navy blue)
Black text (normally)
 
Fonts:
Proxima Nova
11-12 pt font[](url)

Logos: https://drive.google.com/drive/folders/1qgQLIAw57zpxdU1OKogO6Ghp5rFz7hYo?usp=sharing
Background Graphics: https://www.dropbox.com/sh/6tmfs885ghg7ro6/AAAt9VdrAXtaz51rJoyDxKX6a?dl=0
Guidelines for Copy Editing: https://drive.google.com/drive/u/0/folders/1qgQLIAw57zpxdU1OKogO6Ghp5rFz7hYo

What font source is being used?  Chamber uses FontAwesome for other projects.

**Comment by richard0000** [comment]
@jeannekitchens 
- Fontawesome is being used for icons (At this stage, just the hamburger icon for the menu on mobile, Ξ but prepared to use it in other places, when icons are needed)
- The font used is the default in Rails6. But I recommend to incorporate Google Fonts, we can choose one from [here](https://fonts.google.com/), and add it to the project.

**Comment by richard0000** [comment]
Covered by PR #12
